# Master's Thesis Notebook

This notebook is part of the **Master's Thesis (MSc Dissertation)**: **Fast Simulation of Neutrino Oscillations in Matter**.

**Author**  
Juan Ramon Diaz Santos <diazjuan@alumni.uv.es>

**Supervisors**  
Roberto Ruiz de Austri Bazan <rruiz@ific.uv.es>  
Michele Lucente <michele.lucente@unibo.it>

**Date**  
June 2026


# test7 segment evolution

Notebook equivalent of `tests/1_core/test7_segment_evolution.py`. The original Python test module remains the source of truth; this notebook imports it and runs each `test_*` function in its own cell for interactive inspection.

The notebook uses the shared TPeanuts output-root convention defined in section `2. Paths`. Generated test artifacts and figures are redirected to the notebook-specific `OUTPUT_DIR` under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`.


## 1. Libraries and test module

This section locates the repository, imports the original Python test module, and reloads it so changes in the source file are reflected when the notebook is rerun. The expected result is that the module imports without errors. Possible problems include running the notebook from outside the repository tree or missing editable installation paths.


In [1]:
from __future__ import annotations

import importlib
import importlib.util
import os
import sys
import traceback
from pathlib import Path

import matplotlib.pyplot as plt


from tpeanuts.util.notebooks import find_repo_root
HERE = Path.cwd().resolve()
PACKAGE_DIR = find_repo_root(HERE, folder="analysis")
print(f"PACKAGE_DIR = {PACKAGE_DIR}")

NOTEBOOK_STEM = "test7_segment_evolution"
TEST_MODULE_PATH = PACKAGE_DIR / "notebooks" / "tests" / "1_core" / f"{NOTEBOOK_STEM}.py"
TEST_MODULE_NAME = f"notebook_tests_{TEST_MODULE_PATH.parent.name.replace('.', '_')}_{NOTEBOOK_STEM}"
if not TEST_MODULE_PATH.exists():
    raise FileNotFoundError(f"Could not find local test module: {TEST_MODULE_PATH}")
spec = importlib.util.spec_from_file_location(TEST_MODULE_NAME, TEST_MODULE_PATH)
if spec is None or spec.loader is None:
    raise ImportError(f"Could not load test module spec from {TEST_MODULE_PATH}")
TEST_MODULE = importlib.util.module_from_spec(spec)
sys.modules[TEST_MODULE_NAME] = TEST_MODULE
spec.loader.exec_module(TEST_MODULE)
print("Loaded local test module:", TEST_MODULE_PATH)

from tpeanuts.util.notebooks import build_notebook_test_runner


PACKAGE_DIR = G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts
Loaded local test module: G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts\notebooks\tests\1_core\test7_segment_evolution.py


## 2. Paths

All outputs are rooted at `DEFAULT_OUTPUT_ROOT` unless `TPEANUTS_OUTPUT_ROOT` is defined in the environment. This notebook writes test figures and any generated artifacts under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`, while data, analysis, benchmark, and external roots are defined with the same shared structure used by the analysis notebooks.


In [2]:
DEFAULT_OUTPUT_ROOT = Path(r"V:\output")
OUTPUT_ROOT = Path(os.environ.get("TPEANUTS_OUTPUT_ROOT", DEFAULT_OUTPUT_ROOT))

OUTPUT_DATA_ROOT = Path(OUTPUT_ROOT / "data")
OUTPUT_ANALYSIS_ROOT = Path(OUTPUT_ROOT / "analysis")
OUTPUT_BENCHMARK_ROOT = Path(OUTPUT_ROOT / "benchmark")
OUTPUT_TEST_ROOT = Path(OUTPUT_ROOT / "test")

OUTPUT_DATA_ATMOSPHERE = Path(OUTPUT_DATA_ROOT / "atmosphere")
OUTPUT_DATA_SOLAR = Path(OUTPUT_DATA_ROOT / "solar")
OUTPUT_DATA_EXTERNAL = Path(OUTPUT_DATA_ROOT / "external")

OUTPUT_ANALYSIS_ATMOSPHERE = Path(OUTPUT_ANALYSIS_ROOT / "atmosphere")
OUTPUT_ANALYSIS_SOLAR = Path(OUTPUT_ANALYSIS_ROOT / "solar")
OUTPUT_ANALYSIS_EXTERNAL = Path(OUTPUT_ANALYSIS_ROOT / "external")

OUTPUT_DATA_MCEQ = Path(OUTPUT_DATA_ROOT / "mceq")
OUTPUT_DATA_HONDA = Path(OUTPUT_DATA_ROOT / "honda")

OUTPUT_DIR = OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SHOW_PLOTS = True
print("Output root     :", OUTPUT_ROOT)
print("Output directory:", OUTPUT_DIR)


Output root     : V:\output
Output directory: V:\output\test\core\test7_segment_evolution


In [3]:
NOTEBOOK_RUNNER_ATTRS = {}
if "RUN_REAL_DATA_ANALYSIS" in globals():
    NOTEBOOK_RUNNER_ATTRS["RUN_REAL_mceq_run1_analysis"] = RUN_REAL_DATA_ANALYSIS

runner = build_notebook_test_runner(
    TEST_MODULE,
    OUTPUT_DIR,
    show_plots=SHOW_PLOTS,
    auto_save_figures=True,
    extra_module_attrs=NOTEBOOK_RUNNER_ATTRS,
)
run_notebook_test = runner.run_test
run_notebook_call = runner.run_call


## Test: `test_segment_perturbative_matches_core`

**What is checked:** Segment perturbative matches core behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; High-level segment evolutor matches perturbation core.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [4]:
run_notebook_test(TEST_MODULE.test_segment_perturbative_matches_core)


Running test_segment_perturbative_matches_core ...

------------------------------------------------------------------------------------------
TEST: high-level perturbative_segment_evolutor matches core
------------------------------------------------------------------------------------------
[DEBUG] H Hermitian error: max|H-H†| = 1.1102e-16
U_high:
tensor([[-6.9911714440e-03-9.6678866441e-01j, -2.1469571569e-01-1.3780936135e-01j, 1.2528087086e-02-6.0259011500e-03j],
        [-2.1182459798e-01-1.4226118109e-01j, 8.8999068219e-01-3.7565728281e-01j, 3.4216710122e-02+2.2949951370e-02j],
        [1.2469557157e-02-3.9376648098e-03j, 3.4885400650e-02+2.2421881720e-02j, 6.8064631390e-02-9.9673353864e-01j]], dtype=torch.complex128)
U_ref:
tensor([[-6.9911714440e-03-9.6678866441e-01j, -2.1469571569e-01-1.3780936135e-01j, 1.2528087086e-02-6.0259011500e-03j],
        [-2.1182459798e-01-1.4226118109e-01j, 8.8999068219e-01-3.7565728281e-01j, 3.4216710122e-02+2.2949951370e-02j],
        [1.246955715

## Test: `test_segment_constant_density_matches_evolution_core`

**What is checked:** Segment constant density matches evolution core behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; High-level constant-density segment evolutor matches core.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [5]:
run_notebook_test(TEST_MODULE.test_segment_constant_density_matches_evolution_core)


Running test_segment_constant_density_matches_evolution_core ...

------------------------------------------------------------------------------------------
TEST: constant_density_segment_evolutor matches evolution core
------------------------------------------------------------------------------------------
[DEBUG] H Hermitian error: max|H-H†| = 1.1102e-16
U_high:
tensor([[-6.9976903484e-03-9.6680446748e-01j, -2.1320657853e-01-1.4000189545e-01j, 1.2563376269e-02-4.9739027482e-03j],
        [-2.1320657853e-01-1.4000189545e-01j, 8.9001800894e-01-3.7563934246e-01j, 3.4526050842e-02+2.2658422417e-02j],
        [1.2563376269e-02-4.9739027482e-03j, 3.4526050842e-02+2.2658422417e-02j, 6.8043823541e-02-9.9673567592e-01j]], dtype=torch.complex128)
U_ref:
tensor([[-6.9976903484e-03-9.6680446748e-01j, -2.1320657853e-01-1.4000189545e-01j, 1.2563376269e-02-4.9739027482e-03j],
        [-2.1320657853e-01-1.4000189545e-01j, 8.9001800894e-01-3.7563934246e-01j, 3.4526050842e-02+2.2658422417e-02j],
   

## Test: `test_segment_constant_density_case_perturbative_equals_constant`

**What is checked:** Segment constant density case perturbative equals constant behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Perturbative high-level equals constant-density high-level for b=c=0.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [6]:
run_notebook_test(TEST_MODULE.test_segment_constant_density_case_perturbative_equals_constant)


Running test_segment_constant_density_case_perturbative_equals_constant ...

------------------------------------------------------------------------------------------
TEST: perturbative segment equals constant segment when b=c=0
------------------------------------------------------------------------------------------
U_pert:
tensor([[4.7838992569e-02-9.6533715713e-01j, -2.1026291539e-01-1.4691229002e-01j, 3.8823585845e-03-5.1784740121e-03j],
        [-2.1026291539e-01-1.4691229002e-01j, 8.8943155407e-01-3.7603620937e-01j, 3.3946296645e-02+2.3711057852e-02j],
        [3.8823585845e-03-5.1784740121e-03j, 3.3946296645e-02+2.3711057852e-02j, 7.0971641764e-02-9.9659749721e-01j]], dtype=torch.complex128)
U_const:
tensor([[4.7838992569e-02-9.6533715713e-01j, -2.1026291539e-01-1.4691229002e-01j, 3.8823585845e-03-5.1784740121e-03j],
        [-2.1026291539e-01-1.4691229002e-01j, 8.8943155407e-01-3.7603620937e-01j, 3.3946296645e-02+2.3711057852e-02j],
        [3.8823585845e-03-5.1784740121e-03j

## Test: `test_segment_zero_length_identity`

**What is checked:** Segment zero length identity behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Perturbative high-level zero-length segment is identity; Constant high-level zero-length segment is identity.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [7]:
run_notebook_test(TEST_MODULE.test_segment_zero_length_identity)


Running test_segment_zero_length_identity ...

------------------------------------------------------------------------------------------
TEST: zero-length high-level segment gives identity
------------------------------------------------------------------------------------------
U_pert zero length:
tensor([[1.0000000000e+00+0.j, 0.0000000000e+00+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 1.0000000000e+00+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 0.0000000000e+00+0.j, 1.0000000000e+00+0.j]], dtype=torch.complex128)
U_const zero length:
tensor([[1.0000000000e+00+0.j, 0.0000000000e+00+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 1.0000000000e+00+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 0.0000000000e+00+0.j, 1.0000000000e+00+0.j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_segment_zero_length_identity


## Test: `test_segment_unitarity_constant_density`

**What is checked:** Segment unitarity constant density behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Constant-density segment U†U = I; Constant-density segment UU† = I.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [8]:
run_notebook_test(TEST_MODULE.test_segment_unitarity_constant_density)


Running test_segment_unitarity_constant_density ...

------------------------------------------------------------------------------------------
TEST: high-level constant-density segment unitarity
------------------------------------------------------------------------------------------
U†U:
tensor([[ 1.0000000000e+00+0.0000000000e+00j,  1.1721309687e-15-7.9363599026e-17j, -2.8362728832e-16-8.6736173799e-18j],
        [ 1.1721309687e-15+7.9363599026e-17j,  1.0000000000e+00+0.0000000000e+00j, -2.3592239273e-16+2.0816681712e-17j],
        [-2.8362728832e-16+8.6736173799e-18j, -2.3592239273e-16-2.0816681712e-17j,  1.0000000000e+00+0.0000000000e+00j]], dtype=torch.complex128)
UU†:
tensor([[ 1.0000000000e+00+0.0000000000e+00j,  1.1721309687e-15+7.9363599026e-17j, -2.8362728832e-16+8.6736173799e-18j],
        [ 1.1721309687e-15-7.9363599026e-17j,  1.0000000000e+00+0.0000000000e+00j, -2.3592239273e-16-2.0816681712e-17j],
        [-2.8362728832e-16-8.6736173799e-18j, -2.3592239273e-16+2.0816681

## Test: `test_segment_perturbative_near_unitarity`

**What is checked:** Segment perturbative near unitarity behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [9]:
run_notebook_test(TEST_MODULE.test_segment_perturbative_near_unitarity)


Running test_segment_perturbative_near_unitarity ...

------------------------------------------------------------------------------------------
TEST: perturbative high-level segment near-unitarity
------------------------------------------------------------------------------------------
U†U:
tensor([[ 1.0000080971e+00+0.0000000000e+00j, -2.5111775817e-07-3.9888616438e-07j, -1.1027423294e-06-3.2406430406e-07j],
        [-2.5111775817e-07+3.9888616438e-07j,  1.0000072109e+00+0.0000000000e+00j, -2.2437970414e-06+1.6361163600e-06j],
        [-1.1027423294e-06+3.2406430406e-07j, -2.2437970414e-06-1.6361163600e-06j,  1.0000012891e+00+0.0000000000e+00j]], dtype=torch.complex128)
max|U†U-I| = 8.097125e-06
------------------------------------------------------------------------------------------
PASSED: test_segment_perturbative_near_unitarity


## Test: `test_segment_antineutrino_finite_and_different`

**What is checked:** Segment antineutrino finite and different behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [10]:
run_notebook_test(TEST_MODULE.test_segment_antineutrino_finite_and_different)


Running test_segment_antineutrino_finite_and_different ...

------------------------------------------------------------------------------------------
TEST: antineutrino high-level segment
------------------------------------------------------------------------------------------
U_nu:
tensor([[-6.9911714440e-03-9.6678866441e-01j, -2.1469571569e-01-1.3780936135e-01j, 1.2528087086e-02-6.0259011500e-03j],
        [-2.1182459798e-01-1.4226118109e-01j, 8.8999068219e-01-3.7565728281e-01j, 3.4216710122e-02+2.2949951370e-02j],
        [1.2469557157e-02-3.9376648098e-03j, 3.4885400650e-02+2.2421881720e-02j, 6.8064631390e-02-9.9673353864e-01j]], dtype=torch.complex128)
U_anti:
tensor([[3.3101710294e-01+8.7281251120e-01j, 9.5172237415e-02-2.2274836247e-01j, -2.8010080180e-02-2.6300874639e-01j],
        [9.0382780781e-02-2.2470163134e-01j, 8.8053707633e-01-4.0598452155e-01j, -1.2696315610e-02+3.1887134476e-02j],
        [-2.7781783797e-02-2.6306088224e-01j, -1.3267881685e-02+3.1420382953e-02j, 1.3

## Test: `test_segment_batch_shapes_and_finiteness`

**What is checked:** Segment batch shapes and finiteness behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [11]:
run_notebook_test(TEST_MODULE.test_segment_batch_shapes_and_finiteness)


Running test_segment_batch_shapes_and_finiteness ...

------------------------------------------------------------------------------------------
TEST: batched high-level segment shapes and finiteness
------------------------------------------------------------------------------------------
U_pert shape: torch.Size([3, 3, 3])
U_const shape: torch.Size([3, 3, 3])
U_pert:
tensor([[[5.4858163554e-01-7.4001867197e-01j, -2.1162637939e-01-2.3935606681e-01j, 3.0091580415e-02+2.2010926924e-01j],
         [-2.1118465105e-01-2.3975045979e-01j, 8.3599297756e-01-4.4333974619e-01j, 3.2920474253e-02+3.7452680061e-02j],
         [2.9988516666e-02+2.2011836299e-01j, 3.3001847730e-02+3.7410261400e-02j, 7.3643737314e-01+6.3703998761e-01j]],

        [[2.8041937568e-01-8.8899270566e-01j, -1.4898329393e-01-1.4720421807e-01j, -1.8227356296e-01+2.3231338937e-01j],
         [-1.4739732740e-01-1.4882297153e-01j, 9.2652137760e-01-3.1070663677e-01j, 2.3624635505e-02+2.4258370191e-02j],
         [-1.8204331799e-0

## Test: `test_segment_batch_zero_length_identity`

**What is checked:** Segment batch zero length identity behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Batch zero-length element 0 is identity; Batch zero-length element 2 is identity; assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [12]:
run_notebook_test(TEST_MODULE.test_segment_batch_zero_length_identity)


Running test_segment_batch_zero_length_identity ...

------------------------------------------------------------------------------------------
TEST: batched high-level segment zero-length identity
------------------------------------------------------------------------------------------
U:
tensor([[[1.0000000000e+00+0.0000000000e+00j, 0.0000000000e+00+0.0000000000e+00j, 0.0000000000e+00+0.0000000000e+00j],
         [0.0000000000e+00+0.0000000000e+00j, 1.0000000000e+00+0.0000000000e+00j, 0.0000000000e+00+0.0000000000e+00j],
         [0.0000000000e+00+0.0000000000e+00j, 0.0000000000e+00+0.0000000000e+00j, 1.0000000000e+00+0.0000000000e+00j]],

        [[-6.9911714440e-03-9.6678866441e-01j, -2.1469571569e-01-1.3780936135e-01j, 1.2528087086e-02-6.0259011500e-03j],
         [-2.1182459798e-01-1.4226118109e-01j, 8.8999068219e-01-3.7565728281e-01j, 3.4216710122e-02+2.2949951370e-02j],
         [1.2469557157e-02-3.9376648098e-03j, 3.4885400650e-02+2.2421881720e-02j, 6.8064631390e-02-9.9673353