# Master's Thesis Notebook

This notebook is part of the **Master's Thesis (MSc Dissertation)**: **Fast Simulation of Neutrino Oscillations in Matter**.

**Author**  
Juan Ramon Diaz Santos <diazjuan@alumni.uv.es>

**Supervisors**  
Roberto Ruiz de Austri Bazan <rruiz@ific.uv.es>  
Michele Lucente <michele.lucente@unibo.it>

**Date**  
June 2026


# test9 core pipeline

Notebook equivalent of `tests/1_core/test9_core_pipeline.py`. The original Python test module remains the source of truth; this notebook imports it and runs each `test_*` function in its own cell for interactive inspection.

The notebook uses the shared TPeanuts output-root convention defined in section `2. Paths`. Generated test artifacts and figures are redirected to the notebook-specific `OUTPUT_DIR` under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`.


## 1. Libraries and test module

This section locates the repository, imports the original Python test module, and reloads it so changes in the source file are reflected when the notebook is rerun. The expected result is that the module imports without errors. Possible problems include running the notebook from outside the repository tree or missing editable installation paths.


In [1]:
from __future__ import annotations

import importlib
import importlib.util
import os
import sys
import traceback
from pathlib import Path

import matplotlib.pyplot as plt


from tpeanuts.util.notebooks import find_repo_root
HERE = Path.cwd().resolve()
PACKAGE_DIR = find_repo_root(HERE, folder="analysis")
print(f"PACKAGE_DIR = {PACKAGE_DIR}")

NOTEBOOK_STEM = "test9_core_pipeline"
TEST_MODULE_PATH = PACKAGE_DIR / "notebooks" / "tests" / "1_core" / f"{NOTEBOOK_STEM}.py"
TEST_MODULE_NAME = f"notebook_tests_{TEST_MODULE_PATH.parent.name.replace('.', '_')}_{NOTEBOOK_STEM}"
if not TEST_MODULE_PATH.exists():
    raise FileNotFoundError(f"Could not find local test module: {TEST_MODULE_PATH}")
spec = importlib.util.spec_from_file_location(TEST_MODULE_NAME, TEST_MODULE_PATH)
if spec is None or spec.loader is None:
    raise ImportError(f"Could not load test module spec from {TEST_MODULE_PATH}")
TEST_MODULE = importlib.util.module_from_spec(spec)
sys.modules[TEST_MODULE_NAME] = TEST_MODULE
spec.loader.exec_module(TEST_MODULE)
print("Loaded local test module:", TEST_MODULE_PATH)

from tpeanuts.util.notebooks import build_notebook_test_runner


PACKAGE_DIR = G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts
Loaded local test module: G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts\notebooks\tests\1_core\test9_core_pipeline.py


## 2. Paths

All outputs are rooted at `DEFAULT_OUTPUT_ROOT` unless `TPEANUTS_OUTPUT_ROOT` is defined in the environment. This notebook writes test figures and any generated artifacts under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`, while data, analysis, benchmark, and external roots are defined with the same shared structure used by the analysis notebooks.


In [2]:
DEFAULT_OUTPUT_ROOT = Path(r"V:\output")
OUTPUT_ROOT = Path(os.environ.get("TPEANUTS_OUTPUT_ROOT", DEFAULT_OUTPUT_ROOT))

OUTPUT_DATA_ROOT = Path(OUTPUT_ROOT / "data")
OUTPUT_ANALYSIS_ROOT = Path(OUTPUT_ROOT / "analysis")
OUTPUT_BENCHMARK_ROOT = Path(OUTPUT_ROOT / "benchmark")
OUTPUT_TEST_ROOT = Path(OUTPUT_ROOT / "test")

OUTPUT_DATA_ATMOSPHERE = Path(OUTPUT_DATA_ROOT / "atmosphere")
OUTPUT_DATA_SOLAR = Path(OUTPUT_DATA_ROOT / "solar")
OUTPUT_DATA_EXTERNAL = Path(OUTPUT_DATA_ROOT / "external")

OUTPUT_ANALYSIS_ATMOSPHERE = Path(OUTPUT_ANALYSIS_ROOT / "atmosphere")
OUTPUT_ANALYSIS_SOLAR = Path(OUTPUT_ANALYSIS_ROOT / "solar")
OUTPUT_ANALYSIS_EXTERNAL = Path(OUTPUT_ANALYSIS_ROOT / "external")

OUTPUT_DATA_MCEQ = Path(OUTPUT_DATA_ROOT / "mceq")
OUTPUT_DATA_HONDA = Path(OUTPUT_DATA_ROOT / "honda")

OUTPUT_DIR = OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SHOW_PLOTS = True
print("Output root     :", OUTPUT_ROOT)
print("Output directory:", OUTPUT_DIR)


Output root     : V:\output
Output directory: V:\output\test\core\test9_core_pipeline


In [3]:
NOTEBOOK_RUNNER_ATTRS = {}
if "RUN_REAL_DATA_ANALYSIS" in globals():
    NOTEBOOK_RUNNER_ATTRS["RUN_REAL_mceq_run1_analysis"] = RUN_REAL_DATA_ANALYSIS

runner = build_notebook_test_runner(
    TEST_MODULE,
    OUTPUT_DIR,
    show_plots=SHOW_PLOTS,
    auto_save_figures=True,
    extra_module_attrs=NOTEBOOK_RUNNER_ATTRS,
)
run_notebook_test = runner.run_test
run_notebook_call = runner.run_call


## Test: `test_core_pipeline_scalar`

**What is checked:** Core pipeline scalar behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Full PMNS unitarity; Reduced PMNS unitarity; Average density consistency; Segment length consistency; and additional consistency checks.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [4]:
run_notebook_test(TEST_MODULE.test_core_pipeline_scalar)


Running test_core_pipeline_scalar ...

peanuts-TORCH core PIPELINE TEST: SCALAR SEGMENT

####################################################################################################
STEP 1: pmns.py: build full and reduced mixing matrices
####################################################################################################
Full PMNS matrix U_PMNS:
tensor([[8.2161011097e-01+0.0000000000e+00j, 5.5011368835e-01+0.0000000000e+00j, 5.4150066116e-02-1.3928218040e-01j],
        [-4.2716898719e-01-8.1394205031e-02j, 5.6953928872e-01-5.4497949504e-02j, 6.9538234941e-01-7.7110546805e-18j],
        [3.5928935214e-01-8.2277741525e-02j, -6.0580116052e-01-5.5089526351e-02j, 7.0293074530e-01-3.1977221788e-18j]], device='cuda:0',
       dtype=torch.complex128)
Reduced matrix U_red = R13 @ R12:
tensor([[8.2161011097e-01+0.j, 5.5011368835e-01+0.j, 1.4943813247e-01+0.j],
        [-5.5636102291e-01+0.j, 8.3094067910e-01+0.j, 0.0000000000e+00+0.j],
        [-1.2417422328e-01+0.j, -8.3

## Test: `test_core_pipeline_batched`

**What is checked:** Core pipeline batched behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [5]:
run_notebook_test(TEST_MODULE.test_core_pipeline_batched)


Running test_core_pipeline_batched ...

peanuts-TORCH core PIPELINE TEST: BATCHED SEGMENTS

####################################################################################################
STEP 1: segment_evolution.py: build batched perturbative segment evolutors
####################################################################################################
U_batch shape: torch.Size([3, 3, 3])
U_batch:
tensor([[[5.4858163554e-01-7.4001867197e-01j, -2.1162637939e-01-2.3935606681e-01j, 3.0091580415e-02+2.2010926924e-01j],
         [-2.1118465105e-01-2.3975045979e-01j, 8.3599297756e-01-4.4333974619e-01j, 3.2920474253e-02+3.7452680061e-02j],
         [2.9988516666e-02+2.2011836299e-01j, 3.3001847730e-02+3.7410261400e-02j, 7.3643737314e-01+6.3703998761e-01j]],

        [[2.8041937568e-01-8.8899270566e-01j, -1.4898329393e-01-1.4720421807e-01j, -1.8227356296e-01+2.3231338937e-01j],
         [-1.4739732740e-01-1.4882297153e-01j, 9.2652137760e-01-3.1070663677e-01j, 2.3624635505e-02+2.4