# Master's Thesis Notebook

This notebook is part of the **Master's Thesis (MSc Dissertation)**: **Fast Simulation of Neutrino Oscillations in Matter**.

**Author**  
Juan Ramon Diaz Santos <diazjuan@alumni.uv.es>

**Supervisors**  
Roberto Ruiz de Austri Bazan <rruiz@ific.uv.es>  
Michele Lucente <michele.lucente@unibo.it>

**Date**  
June 2026


# test4 evolution

Notebook equivalent of `tests/1_core/test4_evolution.py`. The original Python test module remains the source of truth; this notebook imports it and runs each `test_*` function in its own cell for interactive inspection.

The notebook uses the shared TPeanuts output-root convention defined in section `2. Paths`. Generated test artifacts and figures are redirected to the notebook-specific `OUTPUT_DIR` under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`.


## 1. Libraries and test module

This section locates the repository, imports the original Python test module, and reloads it so changes in the source file are reflected when the notebook is rerun. The expected result is that the module imports without errors. Possible problems include running the notebook from outside the repository tree or missing editable installation paths.


In [1]:
from __future__ import annotations

import importlib
import importlib.util
import os
import sys
import traceback
from pathlib import Path

import matplotlib.pyplot as plt


from tpeanuts.util.notebooks import find_repo_root
HERE = Path.cwd().resolve()
PACKAGE_DIR = find_repo_root(HERE, folder="analysis")
print(f"PACKAGE_DIR = {PACKAGE_DIR}")

NOTEBOOK_STEM = "test4_evolution"
TEST_MODULE_PATH = PACKAGE_DIR / "notebooks" / "tests" / "1_core" / f"{NOTEBOOK_STEM}.py"
TEST_MODULE_NAME = f"notebook_tests_{TEST_MODULE_PATH.parent.name.replace('.', '_')}_{NOTEBOOK_STEM}"
if not TEST_MODULE_PATH.exists():
    raise FileNotFoundError(f"Could not find local test module: {TEST_MODULE_PATH}")
spec = importlib.util.spec_from_file_location(TEST_MODULE_NAME, TEST_MODULE_PATH)
if spec is None or spec.loader is None:
    raise ImportError(f"Could not load test module spec from {TEST_MODULE_PATH}")
TEST_MODULE = importlib.util.module_from_spec(spec)
sys.modules[TEST_MODULE_NAME] = TEST_MODULE
spec.loader.exec_module(TEST_MODULE)
print("Loaded local test module:", TEST_MODULE_PATH)

from tpeanuts.util.notebooks import build_notebook_test_runner


PACKAGE_DIR = G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts
Loaded local test module: G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts\notebooks\tests\1_core\test4_evolution.py


## 2. Paths

All outputs are rooted at `DEFAULT_OUTPUT_ROOT` unless `TPEANUTS_OUTPUT_ROOT` is defined in the environment. This notebook writes test figures and any generated artifacts under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`, while data, analysis, benchmark, and external roots are defined with the same shared structure used by the analysis notebooks.


In [2]:
DEFAULT_OUTPUT_ROOT = Path(r"V:\output")
OUTPUT_ROOT = Path(os.environ.get("TPEANUTS_OUTPUT_ROOT", DEFAULT_OUTPUT_ROOT))

OUTPUT_DATA_ROOT = Path(OUTPUT_ROOT / "data")
OUTPUT_ANALYSIS_ROOT = Path(OUTPUT_ROOT / "analysis")
OUTPUT_BENCHMARK_ROOT = Path(OUTPUT_ROOT / "benchmark")
OUTPUT_TEST_ROOT = Path(OUTPUT_ROOT / "test")

OUTPUT_DATA_ATMOSPHERE = Path(OUTPUT_DATA_ROOT / "atmosphere")
OUTPUT_DATA_SOLAR = Path(OUTPUT_DATA_ROOT / "solar")
OUTPUT_DATA_EXTERNAL = Path(OUTPUT_DATA_ROOT / "external")

OUTPUT_ANALYSIS_ATMOSPHERE = Path(OUTPUT_ANALYSIS_ROOT / "atmosphere")
OUTPUT_ANALYSIS_SOLAR = Path(OUTPUT_ANALYSIS_ROOT / "solar")
OUTPUT_ANALYSIS_EXTERNAL = Path(OUTPUT_ANALYSIS_ROOT / "external")

OUTPUT_DATA_MCEQ = Path(OUTPUT_DATA_ROOT / "mceq")
OUTPUT_DATA_HONDA = Path(OUTPUT_DATA_ROOT / "honda")

OUTPUT_DIR = OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SHOW_PLOTS = True
print("Output root     :", OUTPUT_ROOT)
print("Output directory:", OUTPUT_DIR)


Output root     : V:\output
Output directory: V:\output\test\core\test4_evolution


In [3]:
NOTEBOOK_RUNNER_ATTRS = {}
if "RUN_REAL_DATA_ANALYSIS" in globals():
    NOTEBOOK_RUNNER_ATTRS["RUN_REAL_mceq_run1_analysis"] = RUN_REAL_DATA_ANALYSIS

runner = build_notebook_test_runner(
    TEST_MODULE,
    OUTPUT_DIR,
    show_plots=SHOW_PLOTS,
    auto_save_figures=True,
    extra_module_attrs=NOTEBOOK_RUNNER_ATTRS,
)
run_notebook_test = runner.run_test
run_notebook_call = runner.run_call


## Test: `test_identity_evolutor_like_scalar`

**What is checked:** Identity evolutor like scalar behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; Scalar identity evolutor.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [4]:
run_notebook_test(TEST_MODULE.test_identity_evolutor_like_scalar)


Running test_identity_evolutor_like_scalar ...

------------------------------------------------------------------------------------------
TEST: identity_evolutor_like scalar
------------------------------------------------------------------------------------------
I:
tensor([[1.0000000000e+00+0.j, 0.0000000000e+00+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 1.0000000000e+00+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 0.0000000000e+00+0.j, 1.0000000000e+00+0.j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_identity_evolutor_like_scalar


## Test: `test_identity_evolutor_like_batch`

**What is checked:** Identity evolutor like batch behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; Batch identity evolutor.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [5]:
run_notebook_test(TEST_MODULE.test_identity_evolutor_like_batch)


Running test_identity_evolutor_like_batch ...

------------------------------------------------------------------------------------------
TEST: identity_evolutor_like batch
------------------------------------------------------------------------------------------
I batch shape: torch.Size([3, 3, 3])
tensor([[[1.0000000000e+00+0.j, 0.0000000000e+00+0.j, 0.0000000000e+00+0.j],
         [0.0000000000e+00+0.j, 1.0000000000e+00+0.j, 0.0000000000e+00+0.j],
         [0.0000000000e+00+0.j, 0.0000000000e+00+0.j, 1.0000000000e+00+0.j]],

        [[1.0000000000e+00+0.j, 0.0000000000e+00+0.j, 0.0000000000e+00+0.j],
         [0.0000000000e+00+0.j, 1.0000000000e+00+0.j, 0.0000000000e+00+0.j],
         [0.0000000000e+00+0.j, 0.0000000000e+00+0.j, 1.0000000000e+00+0.j]],

        [[1.0000000000e+00+0.j, 0.0000000000e+00+0.j, 0.0000000000e+00+0.j],
         [0.0000000000e+00+0.j, 1.0000000000e+00+0.j, 0.0000000000e+00+0.j],
         [0.0000000000e+00+0.j, 0.0000000000e+00+0.j, 1.0000000000e+00+0.j]]], 

## Test: `test_enforce_identity_for_zero_length_scalar`

**What is checked:** Enforce identity for zero length scalar behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Scalar zero-length segment gives identity.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [6]:
run_notebook_test(TEST_MODULE.test_enforce_identity_for_zero_length_scalar)


Running test_enforce_identity_for_zero_length_scalar ...

------------------------------------------------------------------------------------------
TEST: enforce_identity_for_zero_length scalar
------------------------------------------------------------------------------------------
U corrected:
tensor([[1.0000000000e+00+0.j, 0.0000000000e+00+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 1.0000000000e+00+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 0.0000000000e+00+0.j, 1.0000000000e+00+0.j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_enforce_identity_for_zero_length_scalar


## Test: `test_enforce_identity_for_zero_length_batch`

**What is checked:** Enforce identity for zero length batch behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Batch element 0 replaced by identity; Batch element 2 replaced by identity; Batch element 1 remains unchanged.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [7]:
run_notebook_test(TEST_MODULE.test_enforce_identity_for_zero_length_batch)


Running test_enforce_identity_for_zero_length_batch ...

------------------------------------------------------------------------------------------
TEST: enforce_identity_for_zero_length batch
------------------------------------------------------------------------------------------
zero_mask: tensor([ True, False,  True])
U corrected:
tensor([[[1.0000000000e+00+0.j, 0.0000000000e+00+0.j, 0.0000000000e+00+0.j],
         [0.0000000000e+00+0.j, 1.0000000000e+00+0.j, 0.0000000000e+00+0.j],
         [0.0000000000e+00+0.j, 0.0000000000e+00+0.j, 1.0000000000e+00+0.j]],

        [[1.0000000000e+00+0.j, 1.0000000000e+00+0.j, 1.0000000000e+00+0.j],
         [1.0000000000e+00+0.j, 1.0000000000e+00+0.j, 1.0000000000e+00+0.j],
         [1.0000000000e+00+0.j, 1.0000000000e+00+0.j, 1.0000000000e+00+0.j]],

        [[1.0000000000e+00+0.j, 0.0000000000e+00+0.j, 0.0000000000e+00+0.j],
         [0.0000000000e+00+0.j, 1.0000000000e+00+0.j, 0.0000000000e+00+0.j],
         [0.0000000000e+00+0.j, 0.00000000

## Test: `test_constant_density_evolutor_from_spectral_vs_matrix_exp`

**What is checked:** Constant density evolutor from spectral vs matrix exp behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Spectral evolutor equals torch.matrix_exp.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [8]:
run_notebook_test(TEST_MODULE.test_constant_density_evolutor_from_spectral_vs_matrix_exp)


Running test_constant_density_evolutor_from_spectral_vs_matrix_exp ...

------------------------------------------------------------------------------------------
TEST: constant_density_evolutor_from_spectral vs matrix_exp
------------------------------------------------------------------------------------------
U_spectral:
tensor([[-6.9976903484e-03-9.6680446748e-01j, -2.1320657853e-01-1.4000189545e-01j, 1.2563376269e-02-4.9739027482e-03j],
        [-2.1320657853e-01-1.4000189545e-01j, 8.9001800894e-01-3.7563934246e-01j, 3.4526050842e-02+2.2658422417e-02j],
        [1.2563376269e-02-4.9739027482e-03j, 3.4526050842e-02+2.2658422417e-02j, 6.8043823541e-02-9.9673567592e-01j]], dtype=torch.complex128)
U_exp:
tensor([[-6.9976903484e-03-9.6680446748e-01j, -2.1320657853e-01-1.4000189545e-01j, 1.2563376269e-02-4.9739027482e-03j],
        [-2.1320657853e-01-1.4000189545e-01j, 8.9001800894e-01-3.7563934246e-01j, 3.4526050842e-02+2.2658422417e-02j],
        [1.2563376269e-02-4.9739027482e-03j, 3

## Test: `test_constant_density_evolutor_high_level_vs_matrix_exp`

**What is checked:** Constant density evolutor high level vs matrix exp behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: constant_density_evolutor equals matrix_exp_evolutor.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [9]:
run_notebook_test(TEST_MODULE.test_constant_density_evolutor_high_level_vs_matrix_exp)


Running test_constant_density_evolutor_high_level_vs_matrix_exp ...

------------------------------------------------------------------------------------------
TEST: constant_density_evolutor high-level vs matrix_exp_evolutor
------------------------------------------------------------------------------------------
U0:
tensor([[-6.9976903484e-03-9.6680446748e-01j, -2.1320657853e-01-1.4000189545e-01j, 1.2563376269e-02-4.9739027482e-03j],
        [-2.1320657853e-01-1.4000189545e-01j, 8.9001800894e-01-3.7563934246e-01j, 3.4526050842e-02+2.2658422417e-02j],
        [1.2563376269e-02-4.9739027482e-03j, 3.4526050842e-02+2.2658422417e-02j, 6.8043823541e-02-9.9673567592e-01j]], dtype=torch.complex128)
U_exp:
tensor([[-6.9976903484e-03-9.6680446748e-01j, -2.1320657853e-01-1.4000189545e-01j, 1.2563376269e-02-4.9739027482e-03j],
        [-2.1320657853e-01-1.4000189545e-01j, 8.9001800894e-01-3.7563934246e-01j, 3.4526050842e-02+2.2658422417e-02j],
        [1.2563376269e-02-4.9739027482e-03j, 3.4526

## Test: `test_matrix_exp_evolutor_direct`

**What is checked:** Matrix exp evolutor direct behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: matrix_exp_evolutor direct formula.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [10]:
run_notebook_test(TEST_MODULE.test_matrix_exp_evolutor_direct)


Running test_matrix_exp_evolutor_direct ...

------------------------------------------------------------------------------------------
TEST: matrix_exp_evolutor direct formula
------------------------------------------------------------------------------------------
U:
tensor([[-6.9976903484e-03-9.6680446748e-01j, -2.1320657853e-01-1.4000189545e-01j, 1.2563376269e-02-4.9739027482e-03j],
        [-2.1320657853e-01-1.4000189545e-01j, 8.9001800894e-01-3.7563934246e-01j, 3.4526050842e-02+2.2658422417e-02j],
        [1.2563376269e-02-4.9739027482e-03j, 3.4526050842e-02+2.2658422417e-02j, 6.8043823541e-02-9.9673567592e-01j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_matrix_exp_evolutor_direct


## Test: `test_unitarity_constant_density_evolutor`

**What is checked:** Unitarity constant density evolutor behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: U0†U0 = I; U0U0† = I.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [11]:
run_notebook_test(TEST_MODULE.test_unitarity_constant_density_evolutor)


Running test_unitarity_constant_density_evolutor ...

------------------------------------------------------------------------------------------
TEST: unitarity of constant_density_evolutor
------------------------------------------------------------------------------------------
U0†U0:
tensor([[ 1.0000000000e+00+0.0000000000e+00j,  1.1721309687e-15-7.9363599026e-17j, -2.8362728832e-16-8.6736173799e-18j],
        [ 1.1721309687e-15+7.9363599026e-17j,  1.0000000000e+00+0.0000000000e+00j, -2.3592239273e-16+2.0816681712e-17j],
        [-2.8362728832e-16+8.6736173799e-18j, -2.3592239273e-16-2.0816681712e-17j,  1.0000000000e+00+0.0000000000e+00j]], dtype=torch.complex128)
U0U0†:
tensor([[ 1.0000000000e+00+0.0000000000e+00j,  1.1721309687e-15+7.9363599026e-17j, -2.8362728832e-16+8.6736173799e-18j],
        [ 1.1721309687e-15-7.9363599026e-17j,  1.0000000000e+00+0.0000000000e+00j, -2.3592239273e-16-2.0816681712e-17j],
        [-2.8362728832e-16-8.6736173799e-18j, -2.3592239273e-16+2.081668171

## Test: `test_zero_length_constant_density_evolutor`

**What is checked:** Zero length constant density evolutor behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Zero-length evolutor is identity.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [12]:
run_notebook_test(TEST_MODULE.test_zero_length_constant_density_evolutor)


Running test_zero_length_constant_density_evolutor ...

------------------------------------------------------------------------------------------
TEST: zero-length constant_density_evolutor
------------------------------------------------------------------------------------------
U0 zero length:
tensor([[1.0000000000e+00+0.j, 0.0000000000e+00+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 1.0000000000e+00+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 0.0000000000e+00+0.j, 1.0000000000e+00+0.j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_zero_length_constant_density_evolutor


## Test: `test_batch_constant_density_evolutor_vs_matrix_exp`

**What is checked:** Batch constant density evolutor vs matrix exp behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; Batched spectral evolutor equals batched matrix_exp.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [13]:
run_notebook_test(TEST_MODULE.test_batch_constant_density_evolutor_vs_matrix_exp)


Running test_batch_constant_density_evolutor_vs_matrix_exp ...

------------------------------------------------------------------------------------------
TEST: batched constant_density_evolutor vs matrix_exp_evolutor
------------------------------------------------------------------------------------------
H batch shape: torch.Size([3, 3, 3])
L batch shape: torch.Size([3])
U0 batch shape: torch.Size([3, 3, 3])
------------------------------------------------------------------------------------------
PASSED: test_batch_constant_density_evolutor_vs_matrix_exp


## Test: `test_batch_unitarity`

**What is checked:** Batch unitarity behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Batched U0†U0 = I; Batched U0U0† = I.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls; probability conservation failures often point to numerical precision or matrix convention issues.


In [14]:
run_notebook_test(TEST_MODULE.test_batch_unitarity)


Running test_batch_unitarity ...

------------------------------------------------------------------------------------------
TEST: batched unitarity
------------------------------------------------------------------------------------------
Batched U0†U0:
tensor([[[ 1.0000000000e+00+0.0000000000e+00j,  1.6740081543e-15-1.0755285551e-16j,  3.0531133177e-16+1.3877787808e-16j],
         [ 1.6740081543e-15+1.0755285551e-16j,  1.0000000000e+00+0.0000000000e+00j, -3.5388358910e-16-2.7755575616e-17j],
         [ 3.0531133177e-16-1.3877787808e-16j, -3.5388358910e-16+2.7755575616e-17j,  1.0000000000e+00+0.0000000000e+00j]],

        [[ 1.0000000000e+00+0.0000000000e+00j,  1.7980408828e-15+7.4593109467e-17j, -6.1062266354e-16+1.6653345369e-16j],
         [ 1.7980408828e-15-7.4593109467e-17j,  1.0000000000e+00+0.0000000000e+00j, -3.1051550220e-16-1.3877787808e-17j],
         [-6.1062266354e-16-1.6653345369e-16j, -3.1051550220e-16+1.3877787808e-17j,  1.0000000000e+00+0.0000000000e+00j]],

        [

## Test: `test_batch_zero_length_enforcement`

**What is checked:** Batch zero length enforcement behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Batch zero-length element 0 is identity; Batch zero-length element 2 is identity; assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [15]:
run_notebook_test(TEST_MODULE.test_batch_zero_length_enforcement)


Running test_batch_zero_length_enforcement ...

------------------------------------------------------------------------------------------
TEST: batched zero-length enforcement
------------------------------------------------------------------------------------------
L: tensor([0.0000000000e+00, 5.0000000000e-01, 0.0000000000e+00], dtype=torch.float64)
zero_mask: tensor([ True, False,  True])
U0:
tensor([[[1.0000000000e+00+0.0000000000e+00j, 0.0000000000e+00+0.0000000000e+00j, 0.0000000000e+00+0.0000000000e+00j],
         [0.0000000000e+00+0.0000000000e+00j, 1.0000000000e+00+0.0000000000e+00j, 0.0000000000e+00+0.0000000000e+00j],
         [0.0000000000e+00+0.0000000000e+00j, 0.0000000000e+00+0.0000000000e+00j, 1.0000000000e+00+0.0000000000e+00j]],

        [[-6.9976903484e-03-9.6680446748e-01j, -2.1320657853e-01-1.4000189545e-01j, 1.2563376269e-02-4.9739027482e-03j],
         [-2.1320657853e-01-1.4000189545e-01j, 8.9001800894e-01-3.7563934246e-01j, 3.4526050842e-02+2.2658422417e-02j],
