# Master's Thesis Notebook

This notebook is part of the **Master's Thesis (MSc Dissertation)**: **Fast Simulation of Neutrino Oscillations in Matter**.

**Author**  
Juan Ramon Diaz Santos <diazjuan@alumni.uv.es>

**Supervisors**  
Roberto Ruiz de Austri Bazan <rruiz@ific.uv.es>  
Michele Lucente <michele.lucente@unibo.it>

**Date**  
June 2026


# test5 integration

Notebook equivalent of `tests/1_core/test5_integration.py`. The original Python test module remains the source of truth; this notebook imports it and runs each `test_*` function in its own cell for interactive inspection.

The notebook uses the shared TPeanuts output-root convention defined in section `2. Paths`. Generated test artifacts and figures are redirected to the notebook-specific `OUTPUT_DIR` under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`.


## 1. Libraries and test module

This section locates the repository, imports the original Python test module, and reloads it so changes in the source file are reflected when the notebook is rerun. The expected result is that the module imports without errors. Possible problems include running the notebook from outside the repository tree or missing editable installation paths.


In [1]:
from __future__ import annotations

import importlib
import importlib.util
import os
import sys
import traceback
from pathlib import Path

import matplotlib.pyplot as plt


from tpeanuts.util.notebooks import find_repo_root
HERE = Path.cwd().resolve()
PACKAGE_DIR = find_repo_root(HERE, folder="analysis")
print(f"PACKAGE_DIR = {PACKAGE_DIR}")

NOTEBOOK_STEM = "test5_integration"
TEST_MODULE_PATH = PACKAGE_DIR / "notebooks" / "tests" / "1_core" / f"{NOTEBOOK_STEM}.py"
TEST_MODULE_NAME = f"notebook_tests_{TEST_MODULE_PATH.parent.name.replace('.', '_')}_{NOTEBOOK_STEM}"
if not TEST_MODULE_PATH.exists():
    raise FileNotFoundError(f"Could not find local test module: {TEST_MODULE_PATH}")
spec = importlib.util.spec_from_file_location(TEST_MODULE_NAME, TEST_MODULE_PATH)
if spec is None or spec.loader is None:
    raise ImportError(f"Could not load test module spec from {TEST_MODULE_PATH}")
TEST_MODULE = importlib.util.module_from_spec(spec)
sys.modules[TEST_MODULE_NAME] = TEST_MODULE
spec.loader.exec_module(TEST_MODULE)
print("Loaded local test module:", TEST_MODULE_PATH)

from tpeanuts.util.notebooks import build_notebook_test_runner


PACKAGE_DIR = G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts
Loaded local test module: G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts\notebooks\tests\1_core\test5_integration.py


## 2. Paths

All outputs are rooted at `DEFAULT_OUTPUT_ROOT` unless `TPEANUTS_OUTPUT_ROOT` is defined in the environment. This notebook writes test figures and any generated artifacts under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`, while data, analysis, benchmark, and external roots are defined with the same shared structure used by the analysis notebooks.


In [2]:
DEFAULT_OUTPUT_ROOT = Path(r"V:\output")
OUTPUT_ROOT = Path(os.environ.get("TPEANUTS_OUTPUT_ROOT", DEFAULT_OUTPUT_ROOT))

OUTPUT_DATA_ROOT = Path(OUTPUT_ROOT / "data")
OUTPUT_ANALYSIS_ROOT = Path(OUTPUT_ROOT / "analysis")
OUTPUT_BENCHMARK_ROOT = Path(OUTPUT_ROOT / "benchmark")
OUTPUT_TEST_ROOT = Path(OUTPUT_ROOT / "test")

OUTPUT_DATA_ATMOSPHERE = Path(OUTPUT_DATA_ROOT / "atmosphere")
OUTPUT_DATA_SOLAR = Path(OUTPUT_DATA_ROOT / "solar")
OUTPUT_DATA_EXTERNAL = Path(OUTPUT_DATA_ROOT / "external")

OUTPUT_ANALYSIS_ATMOSPHERE = Path(OUTPUT_ANALYSIS_ROOT / "atmosphere")
OUTPUT_ANALYSIS_SOLAR = Path(OUTPUT_ANALYSIS_ROOT / "solar")
OUTPUT_ANALYSIS_EXTERNAL = Path(OUTPUT_ANALYSIS_ROOT / "external")

OUTPUT_DATA_MCEQ = Path(OUTPUT_DATA_ROOT / "mceq")
OUTPUT_DATA_HONDA = Path(OUTPUT_DATA_ROOT / "honda")

OUTPUT_DIR = OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SHOW_PLOTS = True
print("Output root     :", OUTPUT_ROOT)
print("Output directory:", OUTPUT_DIR)


Output root     : V:\output
Output directory: V:\output\test\core\test5_integration


In [3]:
NOTEBOOK_RUNNER_ATTRS = {}
if "RUN_REAL_DATA_ANALYSIS" in globals():
    NOTEBOOK_RUNNER_ATTRS["RUN_REAL_mceq_run1_analysis"] = RUN_REAL_DATA_ANALYSIS

runner = build_notebook_test_runner(
    TEST_MODULE,
    OUTPUT_DIR,
    show_plots=SHOW_PLOTS,
    auto_save_figures=True,
    extra_module_attrs=NOTEBOOK_RUNNER_ATTRS,
)
run_notebook_test = runner.run_test
run_notebook_call = runner.run_call


## Test: `test_c1_matches_invariant`

**What is checked:** C1 matches invariant behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: c1 formula matches -Tr(T^2)/2.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [4]:
run_notebook_test(TEST_MODULE.test_c1_matches_invariant)


Running test_c1_matches_invariant ...

------------------------------------------------------------------------------------------
TEST: c1 vs invariant c1
------------------------------------------------------------------------------------------
c1 invariant = -501.40344397969255
c1 formula   = -501.4034439796928
------------------------------------------------------------------------------------------
PASSED: test_c1_matches_invariant


## Test: `test_c0_characteristic_polynomial`

**What is checked:** C0 characteristic polynomial behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Characteristic polynomial residual.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [5]:
run_notebook_test(TEST_MODULE.test_c0_characteristic_polynomial)


Running test_c0_characteristic_polynomial ...

------------------------------------------------------------------------------------------
TEST: c0 in characteristic polynomial
------------------------------------------------------------------------------------------
lambda:
tensor([-1.4185559215e+01, -1.1628354874e+01, 2.5813914090e+01], dtype=torch.float64)
c0 = <function c0 at 0x000002916BDE7880>
c1 = <function c1 at 0x000002916BDE79A0>
Polynomial residual lambda^3 + c1 lambda + c0:
tensor([ 1.8189894035e-12,  1.8189894035e-12, -1.4551915228e-11], dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_c0_characteristic_polynomial


## Test: `test_lambdas_eigvalsh`

**What is checked:** Lambdas eigvalsh behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: lambdas_eigvalsh equals torch.linalg.eigvalsh.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [6]:
run_notebook_test(TEST_MODULE.test_lambdas_eigvalsh)


Running test_lambdas_eigvalsh ...

------------------------------------------------------------------------------------------
TEST: lambdas_eigvalsh
------------------------------------------------------------------------------------------
lambda eigvalsh:
tensor([-1.4185559215e+01, -1.1628354874e+01, 2.5813914090e+01], dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_lambdas_eigvalsh


## Test: `test_lambdas_cardano_polynomial_residual`

**What is checked:** Lambdas cardano polynomial residual behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; Cardano roots satisfy polynomial.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [7]:
run_notebook_test(TEST_MODULE.test_lambdas_cardano_polynomial_residual)


Running test_lambdas_cardano_polynomial_residual ...

------------------------------------------------------------------------------------------
TEST: lambdas_cardano polynomial residual
------------------------------------------------------------------------------------------
lambda Cardano:
tensor([2.5813914090e+01+0.0000000000e+00j, -1.4185559215e+01-1.9022938184e-15j, -1.1628354874e+01+5.5800618673e-15j], dtype=torch.complex128)
Polynomial residual:
tensor([-5.4569682106e-12+0.0000000000e+00j,  0.0000000000e+00-1.9457959830e-13j,  0.0000000000e+00-5.3427715635e-13j], dtype=torch.complex128)
max residual: 5.4569682106375694e-12
------------------------------------------------------------------------------------------
PASSED: test_lambdas_cardano_polynomial_residual


## Test: `test_Iab_zero_when_la_equals_lb`

**What is checked:** Iab zero when la equals lb behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Iab is zero when la == lb.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [8]:
run_notebook_test(TEST_MODULE.test_Iab_zero_when_la_equals_lb)


Running test_Iab_zero_when_la_equals_lb ...

------------------------------------------------------------------------------------------
TEST: Iab returns zero for la == lb
------------------------------------------------------------------------------------------
Iab:
tensor([[0.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_Iab_zero_when_la_equals_lb


## Test: `test_Iab_polynomial_zero_average_condition`

**What is checked:** Iab polynomial zero average condition behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Integral of perturbation density is zero.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [9]:
run_notebook_test(TEST_MODULE.test_Iab_polynomial_zero_average_condition)


Running test_Iab_polynomial_zero_average_condition ...

------------------------------------------------------------------------------------------
TEST: density perturbation integrates to zero
------------------------------------------------------------------------------------------
naverage = 1.148021666667e+00
atilde   = -4.802166666667e-02
Integral perturbation = 1.843143693225e-17
------------------------------------------------------------------------------------------
PASSED: test_Iab_polynomial_zero_average_condition


## Test: `test_Iab_against_numerical_quadrature_full_branch`

**What is checked:** Iab against numerical quadrature full branch behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Iab full branch matches numerical quadrature.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [10]:
run_notebook_test(TEST_MODULE.test_Iab_against_numerical_quadrature_full_branch)


Running test_Iab_against_numerical_quadrature_full_branch ...

------------------------------------------------------------------------------------------
TEST: Iab against numerical quadrature, full branch
------------------------------------------------------------------------------------------
I analytic:
tensor([[3.1844541209e-03+3.4202080793e-03j]], dtype=torch.complex128)
I numeric:
tensor([[3.1844541311e-03+3.4202080832e-03j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_Iab_against_numerical_quadrature_full_branch


## Test: `test_Iab_against_numerical_quadrature_taylor_branch`

**What is checked:** Iab against numerical quadrature taylor branch behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Iab Taylor branch matches numerical quadrature.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [11]:
run_notebook_test(TEST_MODULE.test_Iab_against_numerical_quadrature_taylor_branch)


Running test_Iab_against_numerical_quadrature_taylor_branch ...

------------------------------------------------------------------------------------------
TEST: Iab against numerical quadrature, Taylor branch
------------------------------------------------------------------------------------------
I analytic Taylor:
tensor([[1.0068376974e-07+1.8428993064e-07j]], dtype=torch.complex128)
I numeric:
tensor([[1.0068919382e-07+1.8428696774e-07j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_Iab_against_numerical_quadrature_taylor_branch


## Test: `test_Iab_batched_shape_and_finiteness`

**What is checked:** Iab batched shape and finiteness behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [12]:
run_notebook_test(TEST_MODULE.test_Iab_batched_shape_and_finiteness)


Running test_Iab_batched_shape_and_finiteness ...

------------------------------------------------------------------------------------------
TEST: Iab batched shape and finiteness
------------------------------------------------------------------------------------------
Iab shape: torch.Size([2, 3, 3])
Iab:
tensor([[[-2.4045787918e-02+9.6486182146e-03j, -2.3140182312e-02+1.1600186870e-02j, -2.2073886920e-02+1.3466494901e-02j],
         [-2.0854957571e-02+1.5234145414e-02j, -1.9492578777e-02+1.6890505407e-02j, -1.7996991053e-02+1.8423801675e-02j],
         [-1.6379410035e-02+1.9823209786e-02j, -1.4651938055e-02+2.1078935408e-02j, -1.2827468903e-02+2.2182287362e-02j]],

        [[-1.2792473301e-02+4.5119458640e-03j, -1.2155285409e-02+6.1027065402e-03j, -1.1337303855e-02+7.5139558018e-03j],
         [-1.0356260940e-02+8.8171338787e-03j, -9.2262667383e-03+9.9934975147e-03j, -7.9635736484e-03+1.1026127391e-02j],
         [-6.5863426425e-03+1.1900171473e-02j, -5.1143820600e-03+1.2603058623e