# Master's Thesis Notebook

This notebook is part of the **Master's Thesis (MSc Dissertation)**: **Fast Simulation of Neutrino Oscillations in Matter**.

**Author**  
Juan Ramon Diaz Santos <diazjuan@alumni.uv.es>

**Supervisors**  
Roberto Ruiz de Austri Bazan <rruiz@ific.uv.es>  
Michele Lucente <michele.lucente@unibo.it>

**Date**  
June 2026


# test1 PMNS

Notebook equivalent of `tests/1_core/test1_PMNS.py`. The original Python test module remains the source of truth; this notebook imports it and runs each `test_*` function in its own cell for interactive inspection.

The notebook uses the shared TPeanuts output-root convention defined in section `2. Paths`. Generated test artifacts and figures are redirected to the notebook-specific `OUTPUT_DIR` under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`.


## 1. Libraries and test module

This section locates the repository, imports the original Python test module, and reloads it so changes in the source file are reflected when the notebook is rerun. The expected result is that the module imports without errors. Possible problems include running the notebook from outside the repository tree or missing editable installation paths.


In [1]:
from __future__ import annotations

import importlib
import importlib.util
import os
import sys
import traceback
from pathlib import Path

import matplotlib.pyplot as plt

from tpeanuts.util.notebooks import build_notebook_test_runner


from tpeanuts.util.notebooks import find_repo_root
HERE = Path.cwd().resolve()
PACKAGE_DIR = find_repo_root(HERE, folder="analysis")
print(f"PACKAGE_DIR = {PACKAGE_DIR}")

NOTEBOOK_STEM = "test1_PMNS"
TEST_MODULE_PATH = PACKAGE_DIR / "notebooks" / "tests" / "1_core" / f"{NOTEBOOK_STEM}.py"
TEST_MODULE_NAME = f"notebook_tests_{TEST_MODULE_PATH.parent.name.replace('.', '_')}_{NOTEBOOK_STEM}"
if not TEST_MODULE_PATH.exists():
    raise FileNotFoundError(f"Could not find local test module: {TEST_MODULE_PATH}")
spec = importlib.util.spec_from_file_location(TEST_MODULE_NAME, TEST_MODULE_PATH)
if spec is None or spec.loader is None:
    raise ImportError(f"Could not load test module spec from {TEST_MODULE_PATH}")
TEST_MODULE = importlib.util.module_from_spec(spec)
sys.modules[TEST_MODULE_NAME] = TEST_MODULE
spec.loader.exec_module(TEST_MODULE)
print("Loaded local test module:", TEST_MODULE_PATH)


PACKAGE_DIR = G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts
Loaded local test module: G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts\notebooks\tests\1_core\test1_PMNS.py


## 2. Paths

All outputs are rooted at `DEFAULT_OUTPUT_ROOT` unless `TPEANUTS_OUTPUT_ROOT` is defined in the environment. This notebook writes test figures and any generated artifacts under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`, while data, analysis, benchmark, and external roots are defined with the same shared structure used by the analysis notebooks.


In [2]:
DEFAULT_OUTPUT_ROOT = Path(r"V:\output")
OUTPUT_ROOT = Path(os.environ.get("TPEANUTS_OUTPUT_ROOT", DEFAULT_OUTPUT_ROOT))

OUTPUT_DATA_ROOT = Path(OUTPUT_ROOT / "data")
OUTPUT_ANALYSIS_ROOT = Path(OUTPUT_ROOT / "analysis")
OUTPUT_BENCHMARK_ROOT = Path(OUTPUT_ROOT / "benchmark")
OUTPUT_TEST_ROOT = Path(OUTPUT_ROOT / "test")

OUTPUT_DATA_ATMOSPHERE = Path(OUTPUT_DATA_ROOT / "atmosphere")
OUTPUT_DATA_SOLAR = Path(OUTPUT_DATA_ROOT / "solar")
OUTPUT_DATA_EXTERNAL = Path(OUTPUT_DATA_ROOT / "external")

OUTPUT_ANALYSIS_ATMOSPHERE = Path(OUTPUT_ANALYSIS_ROOT / "atmosphere")
OUTPUT_ANALYSIS_SOLAR = Path(OUTPUT_ANALYSIS_ROOT / "solar")
OUTPUT_ANALYSIS_EXTERNAL = Path(OUTPUT_ANALYSIS_ROOT / "external")

OUTPUT_DATA_MCEQ = Path(OUTPUT_DATA_ROOT / "mceq")
OUTPUT_DATA_HONDA = Path(OUTPUT_DATA_ROOT / "honda")

OUTPUT_DIR = OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SHOW_PLOTS = True
print("Output root     :", OUTPUT_ROOT)
print("Output directory:", OUTPUT_DIR)


Output root     : V:\output
Output directory: V:\output\test\core\test1_PMNS


In [3]:
NOTEBOOK_RUNNER_ATTRS = {}
if "RUN_REAL_DATA_ANALYSIS" in globals():
    NOTEBOOK_RUNNER_ATTRS["RUN_REAL_mceq_run1_analysis"] = RUN_REAL_DATA_ANALYSIS

runner = build_notebook_test_runner(
    TEST_MODULE,
    OUTPUT_DIR,
    show_plots=SHOW_PLOTS,
    auto_save_figures=True,
    extra_module_attrs=NOTEBOOK_RUNNER_ATTRS,
)
run_notebook_test = runner.run_test
run_notebook_call = runner.run_call


## Test: `test_pmns_shapes_scalar`

**What is checked:** Pmns shapes scalar behavior and numerical consistency.
- pmns = build_pmns()

**Expected result:** The expected result is a clean pass for these checks: Python assert expression.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [4]:
run_notebook_test(TEST_MODULE.test_pmns_shapes_scalar)


Running test_pmns_shapes_scalar ...

------------------------------------------------------------------------------------------
TEST: Scalar shapes
------------------------------------------------------------------------------------------
R12 shape : torch.Size([3, 3])
R13 shape : torch.Size([3, 3])
R23 shape : torch.Size([3, 3])
Delta shape : torch.Size([3, 3])
PMNS shape : torch.Size([3, 3])
Reduced shape : torch.Size([3, 3])
[OK]     All scalar shapes are correct
------------------------------------------------------------------------------------------
PASSED: test_pmns_shapes_scalar


## Test: `test_pmns_dtype`

**What is checked:** Pmns dtype behavior and numerical consistency.
- pmns = build_pmns()

**Expected result:** The expected result is a clean pass for these checks: Python assert expression.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [5]:
run_notebook_test(TEST_MODULE.test_pmns_dtype)


Running test_pmns_dtype ...

------------------------------------------------------------------------------------------
TEST: Dtypes
------------------------------------------------------------------------------------------
theta12 dtype : torch.float64
PMNS dtype    : torch.complex128
Reduced dtype : torch.complex128
[OK]     All dtypes are correct
------------------------------------------------------------------------------------------
PASSED: test_pmns_dtype


## Test: `test_reduced_definition`

**What is checked:** Reduced definition behavior and numerical consistency.
- Ured_expected = pmns.R13() @ pmns.R12()
- Ured = pmns.reduced()

**Expected result:** The expected result is a clean pass for these checks: Ured = R13 @ R12.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [6]:
run_notebook_test(TEST_MODULE.test_reduced_definition)


Running test_reduced_definition ...

------------------------------------------------------------------------------------------
TEST: Reduced matrix definition
------------------------------------------------------------------------------------------
Ured:
tensor([[8.2161011097e-01+0.j, 5.5011368835e-01+0.j, 1.4943813247e-01+0.j],
        [-5.5636102291e-01+0.j, 8.3094067910e-01+0.j, 0.0000000000e+00+0.j],
        [-1.2417422328e-01+0.j, -8.3141552245e-02+0.j, 9.8877107794e-01+0.j]], device='cuda:0', dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_reduced_definition


## Test: `test_full_pmns_definition`

**What is checked:** Full pmns definition behavior and numerical consistency.
- U = pmns.pmns_matrix()

**Expected result:** The expected result is a clean pass for these checks: U_PMNS construction.
- U_expected = (
        pmns.R23()
        @ pmns.Delta()
        @ pmns.R13()
        @ pmns.Delta().conj()
        @ pmns.R12()
    )
  
**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [7]:
run_notebook_test(TEST_MODULE.test_full_pmns_definition)


Running test_full_pmns_definition ...

------------------------------------------------------------------------------------------
TEST: Full PMNS definition
------------------------------------------------------------------------------------------
PMNS matrix:
tensor([[8.2161011097e-01+0.0000000000e+00j, 5.5011368835e-01+0.0000000000e+00j, 5.4150066116e-02-1.3928218040e-01j],
        [-4.2716898719e-01-8.1394205031e-02j, 5.6953928872e-01-5.4497949504e-02j, 6.9538234941e-01-7.7110546805e-18j],
        [3.5928935214e-01-8.2277741525e-02j, -6.0580116052e-01-5.5089526351e-02j, 7.0293074530e-01-3.1977221788e-18j]], device='cuda:0',
       dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_full_pmns_definition


## Test: `test_cached_matrices`

**What is checked:** Cached matrices behavior and numerical consistency.
- pmns = build_pmns()

**Expected result:** The expected result is a clean pass for these checks: Cached reduced matrix; Cached PMNS matrix.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [8]:
run_notebook_test(TEST_MODULE.test_cached_matrices)


Running test_cached_matrices ...

------------------------------------------------------------------------------------------
TEST: Cached matrices
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
PASSED: test_cached_matrices


## Test: `test_pmns_unitarity`

**What is checked:** Pmns unitarity behavior and numerical consistency.
- U = pmns.pmns_matrix()

**Expected result:** The expected result is a clean pass for these checks: 
- U†U = I; UU† = I.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [9]:
run_notebook_test(TEST_MODULE.test_pmns_unitarity)


Running test_pmns_unitarity ...

------------------------------------------------------------------------------------------
TEST: Full PMNS unitarity
------------------------------------------------------------------------------------------
U†U:
tensor([[ 1.0000000000e+00+2.6062966921e-19j, -4.8343890413e-17-5.4756481412e-18j,  1.5063421677e-18-2.2051008763e-17j],
        [-4.8343890413e-17+5.2801559488e-18j,  1.0000000000e+00+1.6432917908e-18j,  2.6821626703e-17-2.2589468801e-17j],
        [ 1.5063421677e-18+2.0902101233e-17j,  2.6821626703e-17+1.7587758704e-17j,  1.0000000000e+00+2.9303160202e-20j]], device='cuda:0',
       dtype=torch.complex128)
UU†:
tensor([[ 1.0000000000e+00-2.9303160202e-20j,  6.1563770143e-17+5.6104496716e-18j, -3.7285809653e-17+3.0123104417e-17j],
        [ 6.1563770143e-17-5.1928955508e-18j,  1.0000000000e+00+1.4756643295e-19j, -2.4243568198e-16-1.8893026904e-18j],
        [-3.7285809653e-17-2.9949947549e-17j, -2.4243568198e-16-8.9085150568e-18j,  1.000000000

## Test: `test_reduced_unitarity`

**What is checked:** Reduced unitarity behavior and numerical consistency.
- left = Ured.conj().transpose(-2, -1) @ Ured
- right = Ured @ Ured.conj().transpose(-2, -1)

**Expected result:** The expected result is a clean pass for these checks: 
- Ured†Ured = I; UredUred† = I.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [10]:
run_notebook_test(TEST_MODULE.test_reduced_unitarity)


Running test_reduced_unitarity ...

------------------------------------------------------------------------------------------
TEST: Reduced matrix unitarity
------------------------------------------------------------------------------------------
Ured† Ured:
tensor([[ 1.0000000000e+00+0.j, -8.6163797029e-17+0.j, -2.9760219075e-18+0.j],
        [-8.6163797029e-17+0.j,  1.0000000000e+00+0.j, -4.9785278217e-18+0.j],
        [-2.9760219075e-18+0.j, -4.9785278217e-18+0.j,  1.0000000000e+00+0.j]], device='cuda:0', dtype=torch.complex128)
Ured Ured†:
tensor([[ 1.0000000000e+00+0.j,  6.9858399874e-18+0.j,  3.0232109506e-18+0.j],
        [ 6.9858399874e-18+0.j,  1.0000000000e+00+0.j, -2.8288278459e-18+0.j],
        [ 3.0232109506e-18+0.j, -2.8288278459e-18+0.j,  1.0000000000e+00+0.j]], device='cuda:0', dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_reduced_unitarity


## Test: `test_dagger`

**What is checked:** Dagger behavior and numerical consistency.
- pmns.dagger()

**Expected result:** The expected result is a clean pass for these checks: dagger() correctness.
- Udagger_expected = U.conj().transpose(-2, -1)

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [11]:
run_notebook_test(TEST_MODULE.test_dagger)


Running test_dagger ...

------------------------------------------------------------------------------------------
TEST: Hermitian conjugate
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
PASSED: test_dagger


## Test: `test_batch_shapes`

**What is checked:** Batch shapes behavior and numerical consistency.
- theta12 = torch.tensor([0.58, 0.59, 0.60], dtype=torch.float64)
- theta13 = torch.tensor([0.14, 0.15, 0.16], dtype=torch.float64)
- theta23 = torch.tensor([0.77, 0.78, 0.79], dtype=torch.float64)
- delta = torch.tensor([0.0, 1.2, math.pi], dtype=torch.float64)
- pmns = PMNS(
        theta12=theta12,
        theta13=theta13,
        theta23=theta23,
        delta=delta,
        real_dtype=torch.float64,
    )

**Expected result:** The expected result is a clean pass for these checks: Python assert expression.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [12]:
run_notebook_test(TEST_MODULE.test_batch_shapes)


Running test_batch_shapes ...

------------------------------------------------------------------------------------------
TEST: Batch shapes
------------------------------------------------------------------------------------------
Batch PMNS shape: torch.Size([3, 3, 3])
Batch Reduced shape: torch.Size([3, 3, 3])
[OK]     Batch shapes are correct
------------------------------------------------------------------------------------------
PASSED: test_batch_shapes


## Test: `test_batch_unitarity`

**What is checked:** Batch unitarity behavior and numerical consistency.
- U = pmns.pmns_matrix()

**Expected result:** The expected result is a clean pass for these checks: Batch unitarity.
- U†U = I

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls; probability conservation failures often point to numerical precision or matrix convention issues.


In [13]:
run_notebook_test(TEST_MODULE.test_batch_unitarity)


Running test_batch_unitarity ...

------------------------------------------------------------------------------------------
TEST: Batch unitarity
------------------------------------------------------------------------------------------
Batch U†U:
tensor([[[ 1.0000000000e+00+0.0000000000e+00j, -5.3977640853e-17+0.0000000000e+00j,  1.0268476499e-17+0.0000000000e+00j],
         [-5.3977640853e-17+0.0000000000e+00j,  1.0000000000e+00+0.0000000000e+00j,  1.2662626657e-17+0.0000000000e+00j],
         [ 1.0268476499e-17+0.0000000000e+00j,  1.2662626657e-17+0.0000000000e+00j,  1.0000000000e+00+0.0000000000e+00j]],

        [[ 1.0000000000e+00+2.6062966921e-19j, -4.8343890413e-17-5.4756481412e-18j,  1.5063421677e-18-2.2051008763e-17j],
         [-4.8343890413e-17+5.2801559488e-18j,  1.0000000000e+00+1.6432917908e-18j,  2.6821626703e-17-2.2589468801e-17j],
         [ 1.5063421677e-18+2.0902101233e-17j,  2.6821626703e-17+1.7587758704e-17j,  1.0000000000e+00+2.9303160202e-20j]],

        [[ 1.00

## Test: `test_zero_angles_identity`

**What is checked:** Zero angles identity behavior and numerical consistency.
- pmns = PMNS(
        theta12=0.0,
        theta13=0.0,
        theta23=0.0,
        delta=0.0,
        real_dtype=torch.float64,
    )

**Expected result:** The expected result is a clean pass for these checks:
- R12 identity; R13 identity; R23 identity; Delta identity; and additional consistency checks.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [14]:
run_notebook_test(TEST_MODULE.test_zero_angles_identity)


Running test_zero_angles_identity ...

------------------------------------------------------------------------------------------
TEST: Zero-angle identity limit
------------------------------------------------------------------------------------------
------------------------------------------------------------------------------------------
PASSED: test_zero_angles_identity
