# Master's Thesis Notebook

This notebook is part of the **Master's Thesis (MSc Dissertation)**: **Fast Simulation of Neutrino Oscillations in Matter**.

**Author**  
Juan Ramon Diaz Santos <diazjuan@alumni.uv.es>

**Supervisors**  
Roberto Ruiz de Austri Bazan <rruiz@ific.uv.es>  
Michele Lucente <michele.lucente@unibo.it>

**Date**  
June 2026


# test2 hamiltonian

Notebook equivalent of `tests/1_core/test2_hamiltonian.py`. The original Python test module remains the source of truth; this notebook imports it and runs each `test_*` function in its own cell for interactive inspection.

The notebook uses the shared TPeanuts output-root convention defined in section `2. Paths`. Generated test artifacts and figures are redirected to the notebook-specific `OUTPUT_DIR` under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`.


## 1. Libraries and test module

This section locates the repository, imports the original Python test module, and reloads it so changes in the source file are reflected when the notebook is rerun. The expected result is that the module imports without errors. Possible problems include running the notebook from outside the repository tree or missing editable installation paths.


In [1]:
from __future__ import annotations

import importlib
import importlib.util
import os
import sys
import traceback
from pathlib import Path

import matplotlib.pyplot as plt


from tpeanuts.util.notebooks import find_repo_root
HERE = Path.cwd().resolve()
PACKAGE_DIR = find_repo_root(HERE, folder="analysis")
print(f"PACKAGE_DIR = {PACKAGE_DIR}")

NOTEBOOK_STEM = "test2_hamiltonian"
TEST_MODULE_PATH = PACKAGE_DIR / "notebooks" / "tests" / "1_core" / f"{NOTEBOOK_STEM}.py"
TEST_MODULE_NAME = f"notebook_tests_{TEST_MODULE_PATH.parent.name.replace('.', '_')}_{NOTEBOOK_STEM}"
if not TEST_MODULE_PATH.exists():
    raise FileNotFoundError(f"Could not find local test module: {TEST_MODULE_PATH}")
spec = importlib.util.spec_from_file_location(TEST_MODULE_NAME, TEST_MODULE_PATH)
if spec is None or spec.loader is None:
    raise ImportError(f"Could not load test module spec from {TEST_MODULE_PATH}")
TEST_MODULE = importlib.util.module_from_spec(spec)
sys.modules[TEST_MODULE_NAME] = TEST_MODULE
spec.loader.exec_module(TEST_MODULE)
print("Loaded local test module:", TEST_MODULE_PATH)

from tpeanuts.util.notebooks import build_notebook_test_runner


PACKAGE_DIR = G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts
Loaded local test module: G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts\notebooks\tests\1_core\test2_hamiltonian.py


## 2. Paths

All outputs are rooted at `DEFAULT_OUTPUT_ROOT` unless `TPEANUTS_OUTPUT_ROOT` is defined in the environment. This notebook writes test figures and any generated artifacts under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`, while data, analysis, benchmark, and external roots are defined with the same shared structure used by the analysis notebooks.


In [2]:
DEFAULT_OUTPUT_ROOT = Path(r"V:\output")
OUTPUT_ROOT = Path(os.environ.get("TPEANUTS_OUTPUT_ROOT", DEFAULT_OUTPUT_ROOT))

OUTPUT_DATA_ROOT = Path(OUTPUT_ROOT / "data")
OUTPUT_ANALYSIS_ROOT = Path(OUTPUT_ROOT / "analysis")
OUTPUT_BENCHMARK_ROOT = Path(OUTPUT_ROOT / "benchmark")
OUTPUT_TEST_ROOT = Path(OUTPUT_ROOT / "test")

OUTPUT_DATA_ATMOSPHERE = Path(OUTPUT_DATA_ROOT / "atmosphere")
OUTPUT_DATA_SOLAR = Path(OUTPUT_DATA_ROOT / "solar")
OUTPUT_DATA_EXTERNAL = Path(OUTPUT_DATA_ROOT / "external")

OUTPUT_ANALYSIS_ATMOSPHERE = Path(OUTPUT_ANALYSIS_ROOT / "atmosphere")
OUTPUT_ANALYSIS_SOLAR = Path(OUTPUT_ANALYSIS_ROOT / "solar")
OUTPUT_ANALYSIS_EXTERNAL = Path(OUTPUT_ANALYSIS_ROOT / "external")

OUTPUT_DATA_MCEQ = Path(OUTPUT_DATA_ROOT / "mceq")
OUTPUT_DATA_HONDA = Path(OUTPUT_DATA_ROOT / "honda")

OUTPUT_DIR = OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SHOW_PLOTS = True
print("Output root     :", OUTPUT_ROOT)
print("Output directory:", OUTPUT_DIR)


Output root     : V:\output
Output directory: V:\output\test\core\test2_hamiltonian


In [3]:
NOTEBOOK_RUNNER_ATTRS = {}
if "RUN_REAL_DATA_ANALYSIS" in globals():
    NOTEBOOK_RUNNER_ATTRS["RUN_REAL_mceq_run1_analysis"] = RUN_REAL_DATA_ANALYSIS

runner = build_notebook_test_runner(
    TEST_MODULE,
    OUTPUT_DIR,
    show_plots=SHOW_PLOTS,
    auto_save_figures=True,
    extra_module_attrs=NOTEBOOK_RUNNER_ATTRS,
)
run_notebook_test = runner.run_test
run_notebook_call = runner.run_call


## Test: `test_kinetic_mass_vector_normal_ordering`

**What is checked:** Kinetic mass vector normal ordering behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [4]:
run_notebook_test(TEST_MODULE.test_kinetic_mass_vector_normal_ordering)


Running test_kinetic_mass_vector_normal_ordering ...

------------------------------------------------------------------------------------------
TEST: kinetic_mass_vector normal ordering
------------------------------------------------------------------------------------------
ki normal ordering:
tensor([0.0000000000e+00, 1.1978296101e+00, 4.0632575858e+01], dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_kinetic_mass_vector_normal_ordering


## Test: `test_kinetic_mass_vector_inverted_ordering`

**What is checked:** Kinetic mass vector inverted ordering behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [5]:
run_notebook_test(TEST_MODULE.test_kinetic_mass_vector_inverted_ordering)


Running test_kinetic_mass_vector_inverted_ordering ...

------------------------------------------------------------------------------------------
TEST: kinetic_mass_vector inverted ordering
------------------------------------------------------------------------------------------
ki inverted ordering:
tensor([-1.1978296101e+00, 0.0000000000e+00, -4.0325853991e+01], dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_kinetic_mass_vector_inverted_ordering


## Test: `test_average_polynomial_density`

**What is checked:** Average polynomial density behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Segment length L; Average polynomial density; assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [6]:
run_notebook_test(TEST_MODULE.test_average_polynomial_density)


Running test_average_polynomial_density ...

------------------------------------------------------------------------------------------
TEST: average_polynomial_density
------------------------------------------------------------------------------------------
L          = 5.000000000000e-01
naverage   = 1.148021666667e+00
zero_mask  = False
------------------------------------------------------------------------------------------
PASSED: test_average_polynomial_density


## Test: `test_average_polynomial_density_zero_length`

**What is checked:** Average polynomial density zero length behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Zero segment length; Average density is set to zero; assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [7]:
run_notebook_test(TEST_MODULE.test_average_polynomial_density_zero_length)


Running test_average_polynomial_density_zero_length ...

------------------------------------------------------------------------------------------
TEST: average_polynomial_density zero-length segment
------------------------------------------------------------------------------------------
L          = 0.000000000000e+00
naverage   = 0.000000000000e+00
zero_mask  = True
------------------------------------------------------------------------------------------
PASSED: test_average_polynomial_density_zero_length


## Test: `test_matter_potential_from_polynomial_average`

**What is checked:** Matter potential from polynomial average behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; Antineutrino potential sign flip.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [8]:
run_notebook_test(TEST_MODULE.test_matter_potential_from_polynomial_average)


Running test_matter_potential_from_polynomial_average ...

------------------------------------------------------------------------------------------
TEST: matter_potential_from_polynomial_average
------------------------------------------------------------------------------------------
naverage   = 1.148021666667e+00
L          = 5.000000000000e-01
V neutrino = 2.829073007627e+00
V antinu   = -2.829073007627e+00
zero_mask  = False
------------------------------------------------------------------------------------------
PASSED: test_matter_potential_from_polynomial_average


## Test: `test_reduced_mixing_matrix`

**What is checked:** Reduced mixing matrix behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Reduced mixing matrix extraction; Reduced mixing antineutrino conjugation.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [9]:
run_notebook_test(TEST_MODULE.test_reduced_mixing_matrix)


Running test_reduced_mixing_matrix ...

------------------------------------------------------------------------------------------
TEST: reduced_mixing_matrix
------------------------------------------------------------------------------------------
Ured:
tensor([[8.2161011097e-01+0.j, 5.5011368835e-01+0.j, 1.4943813247e-01+0.j],
        [-5.5636102291e-01+0.j, 8.3094067910e-01+0.j, 0.0000000000e+00+0.j],
        [-1.2417422328e-01+0.j, -8.3141552245e-02+0.j, 9.8877107794e-01+0.j]], device='cuda:0', dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_reduced_mixing_matrix


## Test: `test_kinetic_hamiltonian_reduced`

**What is checked:** Kinetic hamiltonian reduced behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; Hkin = Ured diag(ki) Ured^T.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [10]:
run_notebook_test(TEST_MODULE.test_kinetic_hamiltonian_reduced)


Running test_kinetic_hamiltonian_reduced ...

------------------------------------------------------------------------------------------
TEST: kinetic_hamiltonian_reduced
------------------------------------------------------------------------------------------
Hkin:
tensor([[1.2698900166e+00+0.j, 5.4754209922e-01+0.j, 5.9490881081e+00+0.j],
        [5.4754209922e-01+0.j, 8.2705632199e-01+0.j, -8.2752894562e-02+0.j],
        [5.9490881081e+00+0.j, -8.2752894562e-02+0.j, 3.9733459130e+01+0.j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_kinetic_hamiltonian_reduced


## Test: `test_matter_hamiltonian_reduced`

**What is checked:** Matter hamiltonian reduced behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; Hmat = diag(V, 0, 0).

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [11]:
run_notebook_test(TEST_MODULE.test_matter_hamiltonian_reduced)


Running test_matter_hamiltonian_reduced ...

------------------------------------------------------------------------------------------
TEST: matter_hamiltonian_reduced
------------------------------------------------------------------------------------------
Hmat:
tensor([[1.2345000000e+00+0.j, 0.0000000000e+00+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 0.0000000000e+00+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 0.0000000000e+00+0.j, 0.0000000000e+00+0.j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_matter_hamiltonian_reduced


## Test: `test_reduced_hamiltonian_consistency`

**What is checked:** Reduced hamiltonian consistency behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; Reduced Hamiltonian consistency.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [12]:
run_notebook_test(TEST_MODULE.test_reduced_hamiltonian_consistency)


Running test_reduced_hamiltonian_consistency ...

------------------------------------------------------------------------------------------
TEST: reduced_hamiltonian consistency
------------------------------------------------------------------------------------------
H:
tensor([[1.5198900166e+00+0.j, 5.4754209922e-01+0.j, 5.9490881081e+00+0.j],
        [5.4754209922e-01+0.j, 8.2705632199e-01+0.j, -8.2752894562e-02+0.j],
        [5.9490881081e+00+0.j, -8.2752894562e-02+0.j, 3.9733459130e+01+0.j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_reduced_hamiltonian_consistency


## Test: `test_reduced_hamiltonian_from_polynomial_density_consistency`

**What is checked:** Reduced hamiltonian from polynomial density consistency behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Polynomial-density V consistency; Polynomial-density L consistency; assert_true; Hamiltonian from polynomial density consistency.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [13]:
run_notebook_test(TEST_MODULE.test_reduced_hamiltonian_from_polynomial_density_consistency)


Running test_reduced_hamiltonian_from_polynomial_density_consistency ...

------------------------------------------------------------------------------------------
TEST: reduced_hamiltonian_from_polynomial_density consistency
------------------------------------------------------------------------------------------
L          = 5.000000000000e-01
V          = 2.829073007627e+00
naverage   = 1.148021666667e+00
zero_mask  = False
H:
tensor([[4.0989630242e+00+0.j, 5.4754209922e-01+0.j, 5.9490881081e+00+0.j],
        [5.4754209922e-01+0.j, 8.2705632199e-01+0.j, -8.2752894562e-02+0.j],
        [5.9490881081e+00+0.j, -8.2752894562e-02+0.j, 3.9733459130e+01+0.j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_reduced_hamiltonian_from_polynomial_density_consistency


## Test: `test_batch_reduced_hamiltonian`

**What is checked:** Batch reduced hamiltonian behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [14]:
run_notebook_test(TEST_MODULE.test_batch_reduced_hamiltonian)


Running test_batch_reduced_hamiltonian ...

------------------------------------------------------------------------------------------
TEST: batched reduced_hamiltonian_from_polynomial_density
------------------------------------------------------------------------------------------
H batch shape: torch.Size([3, 3, 3])
ki batch shape: torch.Size([3, 3])
V batch shape: torch.Size([3])
L batch shape: torch.Size([3])
zero_mask: tensor([False, False, False])
------------------------------------------------------------------------------------------
PASSED: test_batch_reduced_hamiltonian


## Test: `test_zero_length_hamiltonian_from_polynomial_density`

**What is checked:** Zero length hamiltonian from polynomial density behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Zero-length L; Zero-length V set to zero; assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [15]:
run_notebook_test(TEST_MODULE.test_zero_length_hamiltonian_from_polynomial_density)


Running test_zero_length_hamiltonian_from_polynomial_density ...

------------------------------------------------------------------------------------------
TEST: zero-length reduced_hamiltonian_from_polynomial_density
------------------------------------------------------------------------------------------
L         = 0.000000000000e+00
V         = 0.000000000000e+00
zero_mask = True
H:
tensor([[1.2698900166e+00+0.j, 5.4754209922e-01+0.j, 5.9490881081e+00+0.j],
        [5.4754209922e-01+0.j, 8.2705632199e-01+0.j, -8.2752894562e-02+0.j],
        [5.9490881081e+00+0.j, -8.2752894562e-02+0.j, 3.9733459130e+01+0.j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_zero_length_hamiltonian_from_polynomial_density
