# Master's Thesis Notebook

This notebook is part of the **Master's Thesis (MSc Dissertation)**: **Fast Simulation of Neutrino Oscillations in Matter**.

**Author**  
Juan Ramon Diaz Santos <diazjuan@alumni.uv.es>

**Supervisors**  
Roberto Ruiz de Austri Bazan <rruiz@ific.uv.es>  
Michele Lucente <michele.lucente@unibo.it>

**Date**  
June 2026


# test8 probabilities

Notebook equivalent of `tests/1_core/test8_probabilities.py`. The original Python test module remains the source of truth; this notebook imports it and runs each `test_*` function in its own cell for interactive inspection.

The notebook uses the shared TPeanuts output-root convention defined in section `2. Paths`. Generated test artifacts and figures are redirected to the notebook-specific `OUTPUT_DIR` under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`.


## 1. Libraries and test module

This section locates the repository, imports the original Python test module, and reloads it so changes in the source file are reflected when the notebook is rerun. The expected result is that the module imports without errors. Possible problems include running the notebook from outside the repository tree or missing editable installation paths.


In [1]:
from __future__ import annotations

import importlib
import importlib.util
import os
import sys
import traceback
from pathlib import Path

import matplotlib.pyplot as plt


from tpeanuts.util.notebooks import find_repo_root
HERE = Path.cwd().resolve()
PACKAGE_DIR = find_repo_root(HERE, folder="analysis")
print(f"PACKAGE_DIR = {PACKAGE_DIR}")

NOTEBOOK_STEM = "test8_probabilities"
TEST_MODULE_PATH = PACKAGE_DIR / "notebooks" / "tests" / "1_core" / f"{NOTEBOOK_STEM}.py"
TEST_MODULE_NAME = f"notebook_tests_{TEST_MODULE_PATH.parent.name.replace('.', '_')}_{NOTEBOOK_STEM}"
if not TEST_MODULE_PATH.exists():
    raise FileNotFoundError(f"Could not find local test module: {TEST_MODULE_PATH}")
spec = importlib.util.spec_from_file_location(TEST_MODULE_NAME, TEST_MODULE_PATH)
if spec is None or spec.loader is None:
    raise ImportError(f"Could not load test module spec from {TEST_MODULE_PATH}")
TEST_MODULE = importlib.util.module_from_spec(spec)
sys.modules[TEST_MODULE_NAME] = TEST_MODULE
spec.loader.exec_module(TEST_MODULE)
print("Loaded local test module:", TEST_MODULE_PATH)

from tpeanuts.util.notebooks import build_notebook_test_runner


PACKAGE_DIR = G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts
Loaded local test module: G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts\notebooks\tests\1_core\test8_probabilities.py


## 2. Paths

All outputs are rooted at `DEFAULT_OUTPUT_ROOT` unless `TPEANUTS_OUTPUT_ROOT` is defined in the environment. This notebook writes test figures and any generated artifacts under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`, while data, analysis, benchmark, and external roots are defined with the same shared structure used by the analysis notebooks.


In [2]:
DEFAULT_OUTPUT_ROOT = Path(r"V:\output")
OUTPUT_ROOT = Path(os.environ.get("TPEANUTS_OUTPUT_ROOT", DEFAULT_OUTPUT_ROOT))

OUTPUT_DATA_ROOT = Path(OUTPUT_ROOT / "data")
OUTPUT_ANALYSIS_ROOT = Path(OUTPUT_ROOT / "analysis")
OUTPUT_BENCHMARK_ROOT = Path(OUTPUT_ROOT / "benchmark")
OUTPUT_TEST_ROOT = Path(OUTPUT_ROOT / "test")

OUTPUT_DATA_ATMOSPHERE = Path(OUTPUT_DATA_ROOT / "atmosphere")
OUTPUT_DATA_SOLAR = Path(OUTPUT_DATA_ROOT / "solar")
OUTPUT_DATA_EXTERNAL = Path(OUTPUT_DATA_ROOT / "external")

OUTPUT_ANALYSIS_ATMOSPHERE = Path(OUTPUT_ANALYSIS_ROOT / "atmosphere")
OUTPUT_ANALYSIS_SOLAR = Path(OUTPUT_ANALYSIS_ROOT / "solar")
OUTPUT_ANALYSIS_EXTERNAL = Path(OUTPUT_ANALYSIS_ROOT / "external")

OUTPUT_DATA_MCEQ = Path(OUTPUT_DATA_ROOT / "mceq")
OUTPUT_DATA_HONDA = Path(OUTPUT_DATA_ROOT / "honda")

OUTPUT_DIR = OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SHOW_PLOTS = True
print("Output root     :", OUTPUT_ROOT)
print("Output directory:", OUTPUT_DIR)


Output root     : V:\output
Output directory: V:\output\test\core\test8_probabilities


In [3]:
NOTEBOOK_RUNNER_ATTRS = {}
if "RUN_REAL_DATA_ANALYSIS" in globals():
    NOTEBOOK_RUNNER_ATTRS["RUN_REAL_mceq_run1_analysis"] = RUN_REAL_DATA_ANALYSIS

runner = build_notebook_test_runner(
    TEST_MODULE,
    OUTPUT_DIR,
    show_plots=SHOW_PLOTS,
    auto_save_figures=True,
    extra_module_attrs=NOTEBOOK_RUNNER_ATTRS,
)
run_notebook_test = runner.run_test
run_notebook_call = runner.run_call


## Test: `test_flavour_index`

**What is checked:** Flavour index behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [4]:
run_notebook_test(TEST_MODULE.test_flavour_index)


Running test_flavour_index ...

------------------------------------------------------------------------------------------
TEST: flavour_index
------------------------------------------------------------------------------------------
'e' -> 0
'electron' -> 0
'nue' -> 0
'nu_e' -> 0
'mu' -> 1
'muon' -> 1
'numu' -> 1
'nu_mu' -> 1
'tau' -> 2
'nutau' -> 2
'nu_tau' -> 2
0 -> 0
1 -> 1
2 -> 2
[OK]     Invalid flavour label raises ValueError
------------------------------------------------------------------------------------------
PASSED: test_flavour_index


## Test: `test_probability_matrix_from_evolutor_identity`

**What is checked:** Probability matrix from evolutor identity behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; Identity evolutor gives identity probability.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [5]:
run_notebook_test(TEST_MODULE.test_probability_matrix_from_evolutor_identity)


Running test_probability_matrix_from_evolutor_identity ...

------------------------------------------------------------------------------------------
TEST: probability_matrix_from_evolutor identity
------------------------------------------------------------------------------------------
P:
tensor([[1.0000000000e+00, 0.0000000000e+00, 0.0000000000e+00],
        [0.0000000000e+00, 1.0000000000e+00, 0.0000000000e+00],
        [0.0000000000e+00, 0.0000000000e+00, 1.0000000000e+00]], dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_probability_matrix_from_evolutor_identity


## Test: `test_probability_matrix_from_known_rotation`

**What is checked:** Probability matrix from known rotation behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Known rotation probability matrix.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [6]:
run_notebook_test(TEST_MODULE.test_probability_matrix_from_known_rotation)


Running test_probability_matrix_from_known_rotation ...

------------------------------------------------------------------------------------------
TEST: probability_matrix_from_evolutor known rotation
------------------------------------------------------------------------------------------
S:
tensor([[9.5533648913e-01+0.j, 2.9552020666e-01+0.j, 0.0000000000e+00+0.j],
        [-2.9552020666e-01+0.j, 9.5533648913e-01+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 0.0000000000e+00+0.j, 1.0000000000e+00+0.j]], dtype=torch.complex128)
P:
tensor([[9.1266780745e-01, 8.7332192545e-02, 0.0000000000e+00],
        [8.7332192545e-02, 9.1266780745e-01, 0.0000000000e+00],
        [0.0000000000e+00, 0.0000000000e+00, 1.0000000000e+00]], dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_probability_matrix_from_known_rotation


## Test: `test_transition_probability`

**What is checked:** Transition probability behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Transition probability from S; Transition probability from P.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [7]:
run_notebook_test(TEST_MODULE.test_transition_probability)


Running test_transition_probability ...

------------------------------------------------------------------------------------------
TEST: transition_probability
------------------------------------------------------------------------------------------
P(e -> mu) from S = 8.733219254516e-02
P(e -> mu) from P = 8.733219254516e-02
Expected           = 8.733219254516e-02
------------------------------------------------------------------------------------------
PASSED: test_transition_probability


## Test: `test_survival_probability`

**What is checked:** Survival probability behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Survival probability P(e -> e).

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [8]:
run_notebook_test(TEST_MODULE.test_survival_probability)


Running test_survival_probability ...

------------------------------------------------------------------------------------------
TEST: survival_probability
------------------------------------------------------------------------------------------
P(e -> e) = 9.126678074548e-01
------------------------------------------------------------------------------------------
PASSED: test_survival_probability


## Test: `test_probability_columns_sum`

**What is checked:** Probability columns sum behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Column sums equal one.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [9]:
run_notebook_test(TEST_MODULE.test_probability_columns_sum)


Running test_probability_columns_sum ...

------------------------------------------------------------------------------------------
TEST: probability_columns_sum
------------------------------------------------------------------------------------------
P:
tensor([[9.1266780745e-01, 8.7332192545e-02, 0.0000000000e+00],
        [8.7332192545e-02, 9.1266780745e-01, 0.0000000000e+00],
        [0.0000000000e+00, 0.0000000000e+00, 1.0000000000e+00]], dtype=torch.float64)
Column sums:
tensor([1.0000000000e+00, 1.0000000000e+00, 1.0000000000e+00], dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_probability_columns_sum


## Test: `test_check_probability_conservation`

**What is checked:** Check probability conservation behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [10]:
run_notebook_test(TEST_MODULE.test_check_probability_conservation)


Running test_check_probability_conservation ...

------------------------------------------------------------------------------------------
TEST: check_probability_conservation
------------------------------------------------------------------------------------------
P:
tensor([[9.1266780745e-01, 8.7332192545e-02, 0.0000000000e+00],
        [8.7332192545e-02, 9.1266780745e-01, 0.0000000000e+00],
        [0.0000000000e+00, 0.0000000000e+00, 1.0000000000e+00]], dtype=torch.float64)
Conservation check: True
P_bad:
tensor([[1.0126678075e+00, 8.7332192545e-02, 0.0000000000e+00],
        [8.7332192545e-02, 9.1266780745e-01, 0.0000000000e+00],
        [0.0000000000e+00, 0.0000000000e+00, 1.0000000000e+00]], dtype=torch.float64)
Conservation check for P_bad: False
------------------------------------------------------------------------------------------
PASSED: test_check_probability_conservation


## Test: `test_check_probability_matrix`

**What is checked:** Check probability matrix behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [11]:
run_notebook_test(TEST_MODULE.test_check_probability_matrix)


Running test_check_probability_matrix ...

------------------------------------------------------------------------------------------
TEST: check_probability_matrix
------------------------------------------------------------------------------------------
P:
tensor([[9.1266780745e-01, 8.7332192545e-02, 0.0000000000e+00],
        [8.7332192545e-02, 9.1266780745e-01, 0.0000000000e+00],
        [0.0000000000e+00, 0.0000000000e+00, 1.0000000000e+00]], dtype=torch.float64)
Probability matrix check: True
P_bad:
tensor([[-1.0000000000e-01, 8.7332192545e-02, 0.0000000000e+00],
        [8.7332192545e-02, 9.1266780745e-01, 0.0000000000e+00],
        [0.0000000000e+00, 0.0000000000e+00, 1.0000000000e+00]], dtype=torch.float64)
Probability matrix check for P_bad: False
------------------------------------------------------------------------------------------
PASSED: test_check_probability_matrix


## Test: `test_normalize_probability_columns`

**What is checked:** Normalize probability columns behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Normalized columns sum to one.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [12]:
run_notebook_test(TEST_MODULE.test_normalize_probability_columns)


Running test_normalize_probability_columns ...

------------------------------------------------------------------------------------------
TEST: normalize_probability_columns
------------------------------------------------------------------------------------------
P:
tensor([[6.0000000000e-01, 2.0000000000e-01, 3.0000000000e-01],
        [3.0000000000e-01, 5.0000000000e-01, 4.0000000000e-01],
        [2.0000000000e-01, 1.0000000000e-01, 5.0000000000e-01]], dtype=torch.float64)
P_norm:
tensor([[5.4545454545e-01, 2.5000000000e-01, 2.5000000000e-01],
        [2.7272727273e-01, 6.2500000000e-01, 3.3333333333e-01],
        [1.8181818182e-01, 1.2500000000e-01, 4.1666666667e-01]], dtype=torch.float64)
Column sums:
tensor([1.0000000000e+00, 1.0000000000e+00, 1.0000000000e+00], dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_normalize_probability_columns


## Test: `test_apply_probability_matrix_to_flux_identity`

**What is checked:** Apply probability matrix to flux identity behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Identity probability leaves flux unchanged.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [13]:
run_notebook_test(TEST_MODULE.test_apply_probability_matrix_to_flux_identity)


Running test_apply_probability_matrix_to_flux_identity ...

------------------------------------------------------------------------------------------
TEST: apply_probability_matrix_to_flux identity
------------------------------------------------------------------------------------------
flux_initial: tensor([1.0000000000e+00, 2.0000000000e+00, 3.0000000000e+00], dtype=torch.float64)
flux_final  : tensor([1.0000000000e+00, 2.0000000000e+00, 3.0000000000e+00], dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_apply_probability_matrix_to_flux_identity


## Test: `test_apply_probability_matrix_to_flux_known_matrix`

**What is checked:** Apply probability matrix to flux known matrix behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: flux transformation flux_final = P @ flux_initial.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [14]:
run_notebook_test(TEST_MODULE.test_apply_probability_matrix_to_flux_known_matrix)


Running test_apply_probability_matrix_to_flux_known_matrix ...

------------------------------------------------------------------------------------------
TEST: apply_probability_matrix_to_flux known matrix
------------------------------------------------------------------------------------------
P:
tensor([[9.1266780745e-01, 8.7332192545e-02, 0.0000000000e+00],
        [8.7332192545e-02, 9.1266780745e-01, 0.0000000000e+00],
        [0.0000000000e+00, 0.0000000000e+00, 1.0000000000e+00]], dtype=torch.float64)
flux_initial: tensor([1.0000000000e+01, 5.0000000000e+00, 1.0000000000e+00], dtype=torch.float64)
flux_final  : tensor([9.5633390373e+00, 5.4366609627e+00, 1.0000000000e+00], dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_apply_probability_matrix_to_flux_known_matrix


## Test: `test_probability_matrix_from_segment_evolutor`

**What is checked:** Probability matrix from segment evolutor behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; probability conservation failures often point to numerical precision or matrix convention issues.


In [15]:
run_notebook_test(TEST_MODULE.test_probability_matrix_from_segment_evolutor)


Running test_probability_matrix_from_segment_evolutor ...

------------------------------------------------------------------------------------------
TEST: probability_matrix_from real segment evolutor
------------------------------------------------------------------------------------------
S:
tensor([[-6.9911714440e-03-9.6678866441e-01j, -2.1469571569e-01-1.3780936135e-01j, 1.2528087086e-02-6.0259011500e-03j],
        [-2.1182459798e-01-1.4226118109e-01j, 8.8999068219e-01-3.7565728281e-01j, 3.4216710122e-02+2.2949951370e-02j],
        [1.2469557157e-02-3.9376648098e-03j, 3.4885400650e-02+2.2421881720e-02j, 6.8064631390e-02-9.9673353864e-01j]], dtype=torch.complex128)
P:
tensor([[9.3472919811e-01, 6.5085670412e-02, 1.9326445071e-04],
        [6.5107903955e-02, 9.3320180852e-01, 1.6974835194e-03],
        [1.7099505984e-04, 1.7197319584e-03, 9.9811054109e-01]], dtype=torch.float64)
Column sums:
tensor([1.0000080971e+00, 1.0000072109e+00, 1.0000012891e+00], dtype=torch.float64)
--------

## Test: `test_batched_probability_matrix_and_flux`

**What is checked:** Batched probability matrix and flux behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true; Batched flux transformation; Batched probability column conservation.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls; probability conservation failures often point to numerical precision or matrix convention issues.


In [16]:
run_notebook_test(TEST_MODULE.test_batched_probability_matrix_and_flux)


Running test_batched_probability_matrix_and_flux ...

------------------------------------------------------------------------------------------
TEST: batched probability matrix and flux
------------------------------------------------------------------------------------------
P shape: torch.Size([3, 3, 3])
flux_initial shape: torch.Size([3, 3])
flux_final shape: torch.Size([3, 3])
P:
tensor([[[9.9003328892e-01, 9.9667110794e-03, 0.0000000000e+00],
         [9.9667110794e-03, 9.9003328892e-01, 0.0000000000e+00],
         [0.0000000000e+00, 0.0000000000e+00, 1.0000000000e+00]],

        [[9.6053049700e-01, 3.9469502999e-02, 0.0000000000e+00],
         [3.9469502999e-02, 9.6053049700e-01, 0.0000000000e+00],
         [0.0000000000e+00, 0.0000000000e+00, 1.0000000000e+00]],

        [[9.1266780745e-01, 8.7332192545e-02, 0.0000000000e+00],
         [8.7332192545e-02, 9.1266780745e-01, 0.0000000000e+00],
         [0.0000000000e+00, 0.0000000000e+00, 1.0000000000e+00]]], dtype=torch.float64)
