# Master's Thesis Notebook

This notebook is part of the **Master's Thesis (MSc Dissertation)**: **Fast Simulation of Neutrino Oscillations in Matter**.

**Author**  
Juan Ramon Diaz Santos <diazjuan@alumni.uv.es>

**Supervisors**  
Roberto Ruiz de Austri Bazan <rruiz@ific.uv.es>  
Michele Lucente <michele.lucente@unibo.it>

**Date**  
June 2026


# test6 perturbation

Notebook equivalent of `tests/1_core/test6_perturbation.py`. The original Python test module remains the source of truth; this notebook imports it and runs each `test_*` function in its own cell for interactive inspection.

The notebook uses the shared TPeanuts output-root convention defined in section `2. Paths`. Generated test artifacts and figures are redirected to the notebook-specific `OUTPUT_DIR` under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`.


## 1. Libraries and test module

This section locates the repository, imports the original Python test module, and reloads it so changes in the source file are reflected when the notebook is rerun. The expected result is that the module imports without errors. Possible problems include running the notebook from outside the repository tree or missing editable installation paths.


In [1]:
from __future__ import annotations

import importlib
import importlib.util
import os
import sys
import traceback
from pathlib import Path

import matplotlib.pyplot as plt


from tpeanuts.util.notebooks import find_repo_root
HERE = Path.cwd().resolve()
PACKAGE_DIR = find_repo_root(HERE, folder="analysis")
print(f"PACKAGE_DIR = {PACKAGE_DIR}")

NOTEBOOK_STEM = "test6_perturbation"
TEST_MODULE_PATH = PACKAGE_DIR / "notebooks" / "tests" / "1_core" / f"{NOTEBOOK_STEM}.py"
TEST_MODULE_NAME = f"notebook_tests_{TEST_MODULE_PATH.parent.name.replace('.', '_')}_{NOTEBOOK_STEM}"
if not TEST_MODULE_PATH.exists():
    raise FileNotFoundError(f"Could not find local test module: {TEST_MODULE_PATH}")
spec = importlib.util.spec_from_file_location(TEST_MODULE_NAME, TEST_MODULE_PATH)
if spec is None or spec.loader is None:
    raise ImportError(f"Could not load test module spec from {TEST_MODULE_PATH}")
TEST_MODULE = importlib.util.module_from_spec(spec)
sys.modules[TEST_MODULE_NAME] = TEST_MODULE
spec.loader.exec_module(TEST_MODULE)
print("Loaded local test module:", TEST_MODULE_PATH)

from tpeanuts.util.notebooks import build_notebook_test_runner


PACKAGE_DIR = G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts
Loaded local test module: G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts\notebooks\tests\1_core\test6_perturbation.py


## 2. Paths

All outputs are rooted at `DEFAULT_OUTPUT_ROOT` unless `TPEANUTS_OUTPUT_ROOT` is defined in the environment. This notebook writes test figures and any generated artifacts under `OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM`, while data, analysis, benchmark, and external roots are defined with the same shared structure used by the analysis notebooks.


In [2]:
DEFAULT_OUTPUT_ROOT = Path(r"V:\output")
OUTPUT_ROOT = Path(os.environ.get("TPEANUTS_OUTPUT_ROOT", DEFAULT_OUTPUT_ROOT))

OUTPUT_DATA_ROOT = Path(OUTPUT_ROOT / "data")
OUTPUT_ANALYSIS_ROOT = Path(OUTPUT_ROOT / "analysis")
OUTPUT_BENCHMARK_ROOT = Path(OUTPUT_ROOT / "benchmark")
OUTPUT_TEST_ROOT = Path(OUTPUT_ROOT / "test")

OUTPUT_DATA_ATMOSPHERE = Path(OUTPUT_DATA_ROOT / "atmosphere")
OUTPUT_DATA_SOLAR = Path(OUTPUT_DATA_ROOT / "solar")
OUTPUT_DATA_EXTERNAL = Path(OUTPUT_DATA_ROOT / "external")

OUTPUT_ANALYSIS_ATMOSPHERE = Path(OUTPUT_ANALYSIS_ROOT / "atmosphere")
OUTPUT_ANALYSIS_SOLAR = Path(OUTPUT_ANALYSIS_ROOT / "solar")
OUTPUT_ANALYSIS_EXTERNAL = Path(OUTPUT_ANALYSIS_ROOT / "external")

OUTPUT_DATA_MCEQ = Path(OUTPUT_DATA_ROOT / "mceq")
OUTPUT_DATA_HONDA = Path(OUTPUT_DATA_ROOT / "honda")

OUTPUT_DIR = OUTPUT_TEST_ROOT / "core" / NOTEBOOK_STEM
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SHOW_PLOTS = True
print("Output root     :", OUTPUT_ROOT)
print("Output directory:", OUTPUT_DIR)


Output root     : V:\output
Output directory: V:\output\test\core\test6_perturbation


In [3]:
NOTEBOOK_RUNNER_ATTRS = {}
if "RUN_REAL_DATA_ANALYSIS" in globals():
    NOTEBOOK_RUNNER_ATTRS["RUN_REAL_mceq_run1_analysis"] = RUN_REAL_DATA_ANALYSIS

runner = build_notebook_test_runner(
    TEST_MODULE,
    OUTPUT_DIR,
    show_plots=SHOW_PLOTS,
    auto_save_figures=True,
    extra_module_attrs=NOTEBOOK_RUNNER_ATTRS,
)
run_notebook_test = runner.run_test
run_notebook_call = runner.run_call


## Test: `test_has_density_perturbation`

**What is checked:** Has density perturbation behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [4]:
run_notebook_test(TEST_MODULE.test_has_density_perturbation)


Running test_has_density_perturbation ...

------------------------------------------------------------------------------------------
TEST: has_density_perturbation
------------------------------------------------------------------------------------------
Case b=0, c=0: False
Case b!=0: True
Case c!=0: True
Batch case: True
------------------------------------------------------------------------------------------
PASSED: test_has_density_perturbation


## Test: `test_polynomial_density_delta_constant`

**What is checked:** Polynomial density delta constant behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: atilde = a - naverage.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [5]:
run_notebook_test(TEST_MODULE.test_polynomial_density_delta_constant)


Running test_polynomial_density_delta_constant ...

------------------------------------------------------------------------------------------
TEST: polynomial_density_delta_constant
------------------------------------------------------------------------------------------
a        = 1.100000000000e+00
naverage = 1.148021666667e+00
atilde   = -4.802166666667e-02
------------------------------------------------------------------------------------------
PASSED: test_polynomial_density_delta_constant


## Test: `test_first_order_integral_Iab_shape_and_finiteness`

**What is checked:** First order integral iab shape and finiteness behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [6]:
run_notebook_test(TEST_MODULE.test_first_order_integral_Iab_shape_and_finiteness)


Running test_first_order_integral_Iab_shape_and_finiteness ...

------------------------------------------------------------------------------------------
TEST: first_order_integral_Iab shape and finiteness
------------------------------------------------------------------------------------------
la:
tensor([[7.0093360989e-01+0.j],
        [3.2581379512e+00+0.j],
        [4.0700406915e+01+0.j]], dtype=torch.complex128)
lb:
tensor([[7.0093360989e-01+0.j, 3.2581379512e+00+0.j, 4.0700406915e+01+0.j]], dtype=torch.complex128)
Iab:
tensor([[0.0000000000e+00+0.0000000000e+00j, -4.3872118804e-03-2.7070933185e-03j, 1.8475330489e-03+8.5238204666e-04j],
        [4.2278001530e-03+2.9498624009e-03j, 0.0000000000e+00+0.0000000000e+00j, 2.7319653796e-03-1.3712610885e-04j],
        [-1.3302522766e-03-1.5395981296e-03j, -2.7301442290e-03-1.6956088482e-04j, 0.0000000000e+00+0.0000000000e+00j]], dtype=torch.complex128)
-------------------------------------------------------------------------------------

## Test: `test_first_order_integral_zero_diagonal`

**What is checked:** First order integral zero diagonal behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Iab diagonal is zero when la = lb.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [7]:
run_notebook_test(TEST_MODULE.test_first_order_integral_zero_diagonal)


Running test_first_order_integral_zero_diagonal ...

------------------------------------------------------------------------------------------
TEST: first_order_integral_Iab diagonal elements
------------------------------------------------------------------------------------------
diag(Iab):
tensor([0.+0.j, 0.+0.j, 0.+0.j], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_first_order_integral_zero_diagonal


## Test: `test_first_order_correction_from_projectors_zero_input`

**What is checked:** First order correction from projectors zero input behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: u1 is zero when Vcorr is zero.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [8]:
run_notebook_test(TEST_MODULE.test_first_order_correction_from_projectors_zero_input)


Running test_first_order_correction_from_projectors_zero_input ...

------------------------------------------------------------------------------------------
TEST: first_order_correction_from_projectors with zero Vcorr
------------------------------------------------------------------------------------------
u1:
tensor([[0.-0.j, 0.-0.j, 0.-0.j],
        [0.-0.j, 0.-0.j, 0.-0.j],
        [0.-0.j, 0.-0.j, 0.-0.j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_first_order_correction_from_projectors_zero_input


## Test: `test_first_order_density_correction_shape_and_finiteness`

**What is checked:** First order density correction shape and finiteness behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [9]:
run_notebook_test(TEST_MODULE.test_first_order_density_correction_shape_and_finiteness)


Running test_first_order_density_correction_shape_and_finiteness ...

------------------------------------------------------------------------------------------
TEST: first_order_density_correction shape and finiteness
------------------------------------------------------------------------------------------
u1:
tensor([[ 6.5189043514e-06+1.5803069911e-05j, -1.4891371575e-03+2.1925340934e-03j, -3.5289182780e-05-1.0519984018e-03j],
        [ 1.3819805510e-03-2.2592856423e-03j, -2.7326752605e-05-1.7940351433e-05j, -3.0934072020e-04+2.9152895281e-04j],
        [-9.3819112229e-05+1.0362379384e-03j,  3.5934980832e-04-2.3654069682e-04j,  2.0807848253e-05+2.1372815213e-06j]], dtype=torch.complex128)
max|u1| = 0.002650421706938809
------------------------------------------------------------------------------------------
PASSED: test_first_order_density_correction_shape_and_finiteness


## Test: `test_first_order_density_correction_zero_for_constant_density`

**What is checked:** First order density correction zero for constant density behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: u1 = 0 for constant density.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [10]:
run_notebook_test(TEST_MODULE.test_first_order_density_correction_zero_for_constant_density)


Running test_first_order_density_correction_zero_for_constant_density ...

------------------------------------------------------------------------------------------
TEST: first_order_density_correction is zero for constant density
------------------------------------------------------------------------------------------
u1 constant density:
tensor([[0.-0.j, 0.-0.j, 0.-0.j],
        [0.-0.j, 0.-0.j, 0.-0.j],
        [0.-0.j, 0.-0.j, 0.-0.j]], dtype=torch.complex128)
max|u1| = 0.0
------------------------------------------------------------------------------------------
PASSED: test_first_order_density_correction_zero_for_constant_density


## Test: `test_perturbative_segment_equals_u0_for_constant_density`

**What is checked:** Perturbative segment equals u0 for constant density behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: U = U0 when b = c = 0.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [11]:
run_notebook_test(TEST_MODULE.test_perturbative_segment_equals_u0_for_constant_density)


Running test_perturbative_segment_equals_u0_for_constant_density ...

------------------------------------------------------------------------------------------
TEST: perturbative_segment_evolutor equals u0 for constant density
------------------------------------------------------------------------------------------
U perturbative:
tensor([[4.7838992569e-02-9.6533715713e-01j, -2.1026291539e-01-1.4691229002e-01j, 3.8823585845e-03-5.1784740121e-03j],
        [-2.1026291539e-01-1.4691229002e-01j, 8.8943155407e-01-3.7603620937e-01j, 3.3946296645e-02+2.3711057852e-02j],
        [3.8823585845e-03-5.1784740121e-03j, 3.3946296645e-02+2.3711057852e-02j, 7.0971641764e-02-9.9659749721e-01j]], dtype=torch.complex128)
U0:
tensor([[4.7838992569e-02-9.6533715713e-01j, -2.1026291539e-01-1.4691229002e-01j, 3.8823585845e-03-5.1784740121e-03j],
        [-2.1026291539e-01-1.4691229002e-01j, 8.8943155407e-01-3.7603620937e-01j, 3.3946296645e-02+2.3711057852e-02j],
        [3.8823585845e-03-5.1784740121e-03

## Test: `test_perturbative_segment_nonconstant_density_finite`

**What is checked:** Perturbative segment nonconstant density finite behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [12]:
run_notebook_test(TEST_MODULE.test_perturbative_segment_nonconstant_density_finite)


Running test_perturbative_segment_nonconstant_density_finite ...

------------------------------------------------------------------------------------------
TEST: perturbative_segment_evolutor non-constant density
------------------------------------------------------------------------------------------
U:
tensor([[-6.9911714440e-03-9.6678866441e-01j, -2.1469571569e-01-1.3780936135e-01j, 1.2528087086e-02-6.0259011500e-03j],
        [-2.1182459798e-01-1.4226118109e-01j, 8.8999068219e-01-3.7565728281e-01j, 3.4216710122e-02+2.2949951370e-02j],
        [1.2469557157e-02-3.9376648098e-03j, 3.4885400650e-02+2.2421881720e-02j, 6.8064631390e-02-9.9673353864e-01j]], dtype=torch.complex128)
U0:
tensor([[-6.9976903484e-03-9.6680446748e-01j, -2.1320657853e-01-1.4000189545e-01j, 1.2563376269e-02-4.9739027482e-03j],
        [-2.1320657853e-01-1.4000189545e-01j, 8.9001800894e-01-3.7563934246e-01j, 3.4526050842e-02+2.2658422417e-02j],
        [1.2563376269e-02-4.9739027482e-03j, 3.4526050842e-02+2.265

## Test: `test_zero_length_perturbative_segment_identity`

**What is checked:** Zero length perturbative segment identity behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Zero-length perturbative evolutor is identity.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change.


In [13]:
run_notebook_test(TEST_MODULE.test_zero_length_perturbative_segment_identity)


Running test_zero_length_perturbative_segment_identity ...

------------------------------------------------------------------------------------------
TEST: zero-length perturbative segment gives identity
------------------------------------------------------------------------------------------
L: tensor(0., dtype=torch.float64)
zero_mask: tensor(True)
U:
tensor([[1.0000000000e+00+0.j, 0.0000000000e+00+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 1.0000000000e+00+0.j, 0.0000000000e+00+0.j],
        [0.0000000000e+00+0.j, 0.0000000000e+00+0.j, 1.0000000000e+00+0.j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_zero_length_perturbative_segment_identity


## Test: `test_batched_perturbative_segment`

**What is checked:** Batched perturbative segment behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [14]:
run_notebook_test(TEST_MODULE.test_batched_perturbative_segment)


Running test_batched_perturbative_segment ...

------------------------------------------------------------------------------------------
TEST: batched perturbative_segment_evolutor
------------------------------------------------------------------------------------------
H shape: torch.Size([3, 3, 3])
L shape: torch.Size([3])
U shape: torch.Size([3, 3, 3])
U:
tensor([[[5.4858163554e-01-7.4001867197e-01j, -2.1162637939e-01-2.3935606681e-01j, 3.0091580415e-02+2.2010926924e-01j],
         [-2.1118465105e-01-2.3975045979e-01j, 8.3599297756e-01-4.4333974619e-01j, 3.2920474253e-02+3.7452680061e-02j],
         [2.9988516666e-02+2.2011836299e-01j, 3.3001847730e-02+3.7410261400e-02j, 7.3643737314e-01+6.3703998761e-01j]],

        [[2.8041937568e-01-8.8899270566e-01j, -1.4898329393e-01-1.4720421807e-01j, -1.8227356296e-01+2.3231338937e-01j],
         [-1.4739732740e-01-1.4882297153e-01j, 9.2652137760e-01-3.1070663677e-01j, 2.3624635505e-02+2.4258370191e-02j],
         [-1.8204331799e-01+2.32474

## Test: `test_batched_zero_length_perturbative_segment`

**What is checked:** Batched zero length perturbative segment behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Batch element 0 zero-length gives identity; Batch element 2 zero-length gives identity; assert_true.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; shape, dtype, or broadcasting changes may break downstream vectorized calls.


In [15]:
run_notebook_test(TEST_MODULE.test_batched_zero_length_perturbative_segment)


Running test_batched_zero_length_perturbative_segment ...

------------------------------------------------------------------------------------------
TEST: batched zero-length perturbative segment
------------------------------------------------------------------------------------------
L: tensor([0.0000000000e+00, 5.0000000000e-01, 0.0000000000e+00], dtype=torch.float64)
zero_mask: tensor([ True, False,  True])
U:
tensor([[[1.0000000000e+00+0.0000000000e+00j, 0.0000000000e+00+0.0000000000e+00j, 0.0000000000e+00+0.0000000000e+00j],
         [0.0000000000e+00+0.0000000000e+00j, 1.0000000000e+00+0.0000000000e+00j, 0.0000000000e+00+0.0000000000e+00j],
         [0.0000000000e+00+0.0000000000e+00j, 0.0000000000e+00+0.0000000000e+00j, 1.0000000000e+00+0.0000000000e+00j]],

        [[-6.9911714440e-03-9.6678866441e-01j, -2.1469571569e-01-1.3780936135e-01j, 1.2528087086e-02-6.0259011500e-03j],
         [-2.1182459798e-01-1.4226118109e-01j, 8.8999068219e-01-3.7565728281e-01j, 3.4216710122e-02+2