# Master's Thesis Notebook

This notebook is part of the **Master's Thesis (MSc Dissertation)**: **Fast Simulation of Neutrino Oscillations in Matter**.

**Author**  
Juan Ramon Diaz Santos <diazjuan@alumni.uv.es>

**Supervisors**  
Roberto Ruiz de Austri Bazan <rruiz@ific.uv.es>  
Michele Lucente <michele.lucente@unibo.it>

**Date**  
June 2026


# test2 coherent evolution

Notebook equivalent of `tests/3_solar/test2_coherent_evolution.py`. The original Python test module remains the source of truth; this notebook imports it and runs each numerical test and diagnostic plot in its own cell for interactive inspection.

The notebook uses the shared TPeanuts output-root convention defined in section `2. Paths`. Generated `solar` test artifacts and figures are redirected to the notebook-specific `OUTPUT_DIR` under `OUTPUT_TEST_ROOT / "solar" / NOTEBOOK_STEM`.


## 1. Libraries and test module

This section locates the repository, imports the original `solar` test module, and reloads it so source changes are reflected when the notebook is rerun. The expected result is that the module imports without errors. Possible problems include running the notebook from outside the repository tree or missing import paths for the editable package.


In [1]:
from __future__ import annotations

import importlib
import importlib.util
import os
import sys
import traceback
from pathlib import Path

import matplotlib.pyplot as plt


from tpeanuts.util.notebooks import find_repo_root
HERE = Path.cwd().resolve()
PACKAGE_DIR = find_repo_root(HERE, folder="analysis")
print(f"PACKAGE_DIR = {PACKAGE_DIR}")

NOTEBOOK_STEM = "test2_coherent_evolution"
TEST_MODULE_PATH = PACKAGE_DIR / "notebooks" / "tests" / "3_solar" / f"{NOTEBOOK_STEM}.py"
TEST_MODULE_NAME = f"notebook_tests_{TEST_MODULE_PATH.parent.name.replace('.', '_')}_{NOTEBOOK_STEM}"
if not TEST_MODULE_PATH.exists():
    raise FileNotFoundError(f"Could not find local test module: {TEST_MODULE_PATH}")
spec = importlib.util.spec_from_file_location(TEST_MODULE_NAME, TEST_MODULE_PATH)
if spec is None or spec.loader is None:
    raise ImportError(f"Could not load test module spec from {TEST_MODULE_PATH}")
TEST_MODULE = importlib.util.module_from_spec(spec)
sys.modules[TEST_MODULE_NAME] = TEST_MODULE
spec.loader.exec_module(TEST_MODULE)
print("Loaded local test module:", TEST_MODULE_PATH)

from tpeanuts.util.notebooks import build_notebook_test_runner


PACKAGE_DIR = G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts
Loaded local test module: G:\Mi unidad\03.Codigo\034.TFM.UV\Tpeanuts\notebooks\tests\3_solar\test2_coherent_evolution.py


## 2. Paths

All outputs are rooted at `DEFAULT_OUTPUT_ROOT` unless `TPEANUTS_OUTPUT_ROOT` is defined in the environment. This notebook writes `solar` test figures and generated artifacts under `OUTPUT_TEST_ROOT / "solar" / NOTEBOOK_STEM`, while data, analysis, benchmark, and external roots follow the same shared structure used by the analysis notebooks.


In [2]:
DEFAULT_OUTPUT_ROOT = Path(r"V:\output")
OUTPUT_ROOT = Path(os.environ.get("TPEANUTS_OUTPUT_ROOT", DEFAULT_OUTPUT_ROOT))

OUTPUT_DATA_ROOT = Path(OUTPUT_ROOT / "data")
OUTPUT_ANALYSIS_ROOT = Path(OUTPUT_ROOT / "analysis")
OUTPUT_BENCHMARK_ROOT = Path(OUTPUT_ROOT / "benchmark")
OUTPUT_TEST_ROOT = Path(OUTPUT_ROOT / "test")

OUTPUT_DATA_ATMOSPHERE = Path(OUTPUT_DATA_ROOT / "atmosphere")
OUTPUT_DATA_SOLAR = Path(OUTPUT_DATA_ROOT / "solar")
OUTPUT_DATA_EXTERNAL = Path(OUTPUT_DATA_ROOT / "external")

OUTPUT_ANALYSIS_ATMOSPHERE = Path(OUTPUT_ANALYSIS_ROOT / "atmosphere")
OUTPUT_ANALYSIS_SOLAR = Path(OUTPUT_ANALYSIS_ROOT / "solar")
OUTPUT_ANALYSIS_EXTERNAL = Path(OUTPUT_ANALYSIS_ROOT / "external")

OUTPUT_DATA_MCEQ = Path(OUTPUT_DATA_ROOT / "mceq")
OUTPUT_DATA_HONDA = Path(OUTPUT_DATA_ROOT / "honda")

OUTPUT_DIR = OUTPUT_TEST_ROOT / "solar" / NOTEBOOK_STEM
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

SHOW_PLOTS = True
print("Output root     :", OUTPUT_ROOT)
print("Output directory:", OUTPUT_DIR)


Output root     : V:\output
Output directory: V:\output\test\solar\test2_coherent_evolution


In [3]:
NOTEBOOK_RUNNER_ATTRS = {}
if "RUN_REAL_DATA_ANALYSIS" in globals():
    NOTEBOOK_RUNNER_ATTRS["RUN_REAL_mceq_run1_analysis"] = RUN_REAL_DATA_ANALYSIS

runner = build_notebook_test_runner(
    TEST_MODULE,
    OUTPUT_DIR,
    show_plots=SHOW_PLOTS,
    auto_save_figures=True,
    extra_module_attrs=NOTEBOOK_RUNNER_ATTRS,
)
run_notebook_test = runner.run_test
run_notebook_call = runner.run_call


## Test: `test_solar_core_coordinate_conversion`

**What is checked:** Solar core coordinate conversion behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: rho to core x conversion.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; missing solar reference tables or changed interpolation grids can affect this check.


In [4]:
run_notebook_test(TEST_MODULE.test_solar_core_coordinate_conversion)


Running test_solar_core_coordinate_conversion ...

solar rho to peanuts core x:
rho: tensor([0.0000, 0.5000, 1.0000], dtype=torch.float64)
x  : tensor([  0.0000,  54.5990, 109.1979], dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_solar_core_coordinate_conversion


## Test: `test_surface_production_is_identity`

**What is checked:** Surface production is identity behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: Surface production returns identity.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; missing solar reference tables or changed interpolation grids can affect this check.


In [5]:
run_notebook_test(TEST_MODULE.test_surface_production_is_identity)


Running test_surface_production_is_identity ...

solar surface evolutor for rho0=1:
tensor([[1.+0.j, 0.+0.j, 0.+0.j],
        [0.+0.j, 1.+0.j, 0.+0.j],
        [0.+0.j, 0.+0.j, 1.+0.j]], dtype=torch.complex128)
------------------------------------------------------------------------------------------
PASSED: test_surface_production_is_identity


## Test: `test_solar_surface_state_norm_conserved`

**What is checked:** Solar surface state norm conserved behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: solar-surface state must be finite; solar-surface norm.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; missing solar reference tables or changed interpolation grids can affect this check.


In [6]:
run_notebook_test(TEST_MODULE.test_solar_surface_state_norm_conserved)


Running test_solar_surface_state_norm_conserved ...

coherent solar-surface state from rho0=0.08:
tensor([-0.2960+0.1947j, -0.4889+0.7836j,  0.0753+0.1256j],
       dtype=torch.complex128)
norm: tensor(1.0000, dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_solar_surface_state_norm_conserved


## Test: `test_solar_to_earth_probabilities_sum_to_one`

**What is checked:** Solar to earth probabilities sum to one behavior and numerical consistency.

**Expected result:** The expected result is a clean pass for these checks: earth-arrival probabilities must have shape (3,); earth-arrival probabilities must be finite; earth-arrival probabilities must be non-negative within tolerance; earth-arrival probability sum.

**Possible problems:** a failed assertion usually indicates a numerical regression or an unexpected API change; missing solar reference tables or changed interpolation grids can affect this check; normalization failures often point to probability conservation or broadcasting issues.


In [7]:
run_notebook_test(TEST_MODULE.test_solar_to_earth_probabilities_sum_to_one)


Running test_solar_to_earth_probabilities_sum_to_one ...

coherent solar-to-earth probabilities:
tensor([0.1730, 0.5762, 0.2508], dtype=torch.float64)
sum: tensor(1.0000, dtype=torch.float64)
------------------------------------------------------------------------------------------
PASSED: test_solar_to_earth_probabilities_sum_to_one
